// <auto-generated />
// <copyright file="OperationTypes.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/operation-kind

using Ignixa.Serialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// Whether an operation is a normal operation or a query.
/// </summary>
public enum OperationTypes
{
    /// <summary>Operation</summary>
    [EnumLiteral("operation", "http://hl7.org/fhir/operation-kind")]
    Operation,
    /// <summary>Query</summary>
    [EnumLiteral("query", "http://hl7.org/fhir/operation-kind")]
    Query,
}
