// <auto-generated />
// <copyright file="SearchModifierCode.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/search-modifier-code

using Ignixa.Serialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// A supported modifier for a search parameter.
/// </summary>
public enum SearchModifierCode
{
    /// <summary>Above</summary>
    [EnumLiteral("above", "http://hl7.org/fhir/search-modifier-code")]
    Above,
    /// <summary>Below</summary>
    [EnumLiteral("below", "http://hl7.org/fhir/search-modifier-code")]
    Below,
    /// <summary>Contains</summary>
    [EnumLiteral("contains", "http://hl7.org/fhir/search-modifier-code")]
    Contains,
    /// <summary>Exact</summary>
    [EnumLiteral("exact", "http://hl7.org/fhir/search-modifier-code")]
    Exact,
    /// <summary>Identifier</summary>
    [EnumLiteral("identifier", "http://hl7.org/fhir/search-modifier-code")]
    Identifier,
    /// <summary>In</summary>
    [EnumLiteral("in", "http://hl7.org/fhir/search-modifier-code")]
    In,
    /// <summary>Missing</summary>
    [EnumLiteral("missing", "http://hl7.org/fhir/search-modifier-code")]
    Missing,
    /// <summary>Not</summary>
    [EnumLiteral("not", "http://hl7.org/fhir/search-modifier-code")]
    Not,
    /// <summary>Not In</summary>
    [EnumLiteral("not-in", "http://hl7.org/fhir/search-modifier-code")]
    NotIn,
    /// <summary>Of Type</summary>
    [EnumLiteral("of-type", "http://hl7.org/fhir/search-modifier-code")]
    OfType,
    /// <summary>Text</summary>
    [EnumLiteral("text", "http://hl7.org/fhir/search-modifier-code")]
    Text,
    /// <summary>Type</summary>
    [EnumLiteral("type", "http://hl7.org/fhir/search-modifier-code")]
    Type,
}
