// <auto-generated />
// <copyright file="SearchComparator.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/search-comparator

using Ignixa.Serialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// What Search Comparator Codes are supported in search.
/// </summary>
public enum SearchComparator
{
    /// <summary>Approximately</summary>
    [EnumLiteral("ap", "http://hl7.org/fhir/search-comparator")]
    Ap,
    /// <summary>Ends Before</summary>
    [EnumLiteral("eb", "http://hl7.org/fhir/search-comparator")]
    Eb,
    /// <summary>Equals</summary>
    [EnumLiteral("eq", "http://hl7.org/fhir/search-comparator")]
    Eq,
    /// <summary>Greater or Equals</summary>
    [EnumLiteral("ge", "http://hl7.org/fhir/search-comparator")]
    Ge,
    /// <summary>Greater Than</summary>
    [EnumLiteral("gt", "http://hl7.org/fhir/search-comparator")]
    Gt,
    /// <summary>Less of Equal</summary>
    [EnumLiteral("le", "http://hl7.org/fhir/search-comparator")]
    Le,
    /// <summary>Less Than</summary>
    [EnumLiteral("lt", "http://hl7.org/fhir/search-comparator")]
    Lt,
    /// <summary>Not Equals</summary>
    [EnumLiteral("ne", "http://hl7.org/fhir/search-comparator")]
    Ne,
    /// <summary>Starts After</summary>
    [EnumLiteral("sa", "http://hl7.org/fhir/search-comparator")]
    Sa,
}
