// <auto-generated />
// <copyright file="ConditionalDeleteStatus.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/conditional-delete-status

using Ignixa.SourceNodeSerialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// A code that indicates how the server supports conditional delete.
/// </summary>
public enum ConditionalDeleteStatus
{
    /// <summary>Multiple Deletes Supported</summary>
    [EnumLiteral("multiple", "http://hl7.org/fhir/conditional-delete-status")]
    Multiple,
    /// <summary>Not Supported</summary>
    [EnumLiteral("not-supported", "http://hl7.org/fhir/conditional-delete-status")]
    NotSupported,
    /// <summary>Single Deletes Supported</summary>
    [EnumLiteral("single", "http://hl7.org/fhir/conditional-delete-status")]
    Single,
}
