// <auto-generated />
// <copyright file="SearchEntryMode.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/search-entry-mode

using Ignixa.SourceNodeSerialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// Why an entry is in the result set - whether it's included as a match or because of an _include requirement, or to convey information or warning information about the search process.
/// </summary>
public enum SearchEntryMode
{
    /// <summary>Include</summary>
    [EnumLiteral("include", "http://hl7.org/fhir/search-entry-mode")]
    Include,
    /// <summary>Match</summary>
    [EnumLiteral("match", "http://hl7.org/fhir/search-entry-mode")]
    Match,
    /// <summary>Outcome</summary>
    [EnumLiteral("outcome", "http://hl7.org/fhir/search-entry-mode")]
    Outcome,
}
