// <auto-generated />
// <copyright file="SearchParamType.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/search-param-type

using Ignixa.SourceNodeSerialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// Data types allowed to be used for search parameters.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifiers should not contain type names", Justification = "Specified in the FHIR spec")]
public enum SearchParamType
{
    /// <summary>Composite</summary>
    [EnumLiteral("composite", "http://hl7.org/fhir/search-param-type")]
    Composite,
    /// <summary>Date/DateTime</summary>
    [EnumLiteral("date", "http://hl7.org/fhir/search-param-type")]
    Date,
    /// <summary>Number</summary>
    [EnumLiteral("number", "http://hl7.org/fhir/search-param-type")]
    Number,
    /// <summary>Quantity</summary>
    [EnumLiteral("quantity", "http://hl7.org/fhir/search-param-type")]
    Quantity,
    /// <summary>Reference</summary>
    [EnumLiteral("reference", "http://hl7.org/fhir/search-param-type")]
    Reference,
    /// <summary>Special</summary>
    [EnumLiteral("special", "http://hl7.org/fhir/search-param-type")]
    Special,
    /// <summary>String</summary>
    [EnumLiteral("string", "http://hl7.org/fhir/search-param-type")]
    String,
    /// <summary>Token</summary>
    [EnumLiteral("token", "http://hl7.org/fhir/search-param-type")]
    Token,
    /// <summary>URI</summary>
    [EnumLiteral("uri", "http://hl7.org/fhir/search-param-type")]
    Uri,
}
