// <auto-generated />
// <copyright file="SpecialValues.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/special-values

using Ignixa.SourceNodeSerialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// A set of generally useful codes defined so they can be included in value sets.
/// </summary>
public enum SpecialValues
{
    [EnumLiteral("false", "http://terminology.hl7.org/CodeSystem/special-values")]
    False,
    /// <summary>Nil Known</summary>
    [EnumLiteral("nil-known", "http://terminology.hl7.org/CodeSystem/special-values")]
    NilKnown,
    /// <summary>Sufficient Quantity</summary>
    [EnumLiteral("sufficient", "http://terminology.hl7.org/CodeSystem/special-values")]
    Sufficient,
    /// <summary>Trace Amount Detected</summary>
    [EnumLiteral("trace", "http://terminology.hl7.org/CodeSystem/special-values")]
    Trace,
    [EnumLiteral("true", "http://terminology.hl7.org/CodeSystem/special-values")]
    True,
    /// <summary>Value Withdrawn</summary>
    [EnumLiteral("withdrawn", "http://terminology.hl7.org/CodeSystem/special-values")]
    Withdrawn,
}
