// <auto-generated />
// <copyright file="SystemRestfulInteraction.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/system-restful-interaction

using Ignixa.SourceNodeSerialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// Operations supported by REST at the system level.
/// </summary>
public enum SystemRestfulInteraction
{
    [EnumLiteral("batch", "http://hl7.org/fhir/restful-interaction")]
    Batch,
    [EnumLiteral("history-system", "http://hl7.org/fhir/restful-interaction")]
    HistorySystem,
    [EnumLiteral("search-system", "http://hl7.org/fhir/restful-interaction")]
    SearchSystem,
    [EnumLiteral("transaction", "http://hl7.org/fhir/restful-interaction")]
    Transaction,
}
