// <auto-generated />
// <copyright file="TypeRestfulInteraction.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/type-restful-interaction

using Ignixa.SourceNodeSerialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// Operations supported by REST at the type or instance level.
/// </summary>
public enum TypeRestfulInteraction
{
    [EnumLiteral("create", "http://hl7.org/fhir/restful-interaction")]
    Create,
    [EnumLiteral("delete", "http://hl7.org/fhir/restful-interaction")]
    Delete,
    [EnumLiteral("history-instance", "http://hl7.org/fhir/restful-interaction")]
    HistoryInstance,
    [EnumLiteral("history-type", "http://hl7.org/fhir/restful-interaction")]
    HistoryType,
    [EnumLiteral("patch", "http://hl7.org/fhir/restful-interaction")]
    Patch,
    [EnumLiteral("read", "http://hl7.org/fhir/restful-interaction")]
    Read,
    [EnumLiteral("search-type", "http://hl7.org/fhir/restful-interaction")]
    SearchType,
    [EnumLiteral("update", "http://hl7.org/fhir/restful-interaction")]
    Update,
    [EnumLiteral("vread", "http://hl7.org/fhir/restful-interaction")]
    Vread,
}
