// <copyright file="CSharpStructureProviderLanguage.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

using System.Text;
using Hl7.Fhir.Model;
using Microsoft.Health.Fhir.CodeGen.Language;
using Microsoft.Health.Fhir.CodeGen.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Packaging;
using Microsoft.Health.Fhir.CodeGen.FhirExtensions;

namespace Ignixa.Specification.Generators;

/// <summary>
/// Custom ILanguage implementation for generating C# IStructureDefinitionSummaryProvider implementations.
/// </summary>
public sealed class CSharpStructureProviderLanguage : ILanguage
{
    private const string LanguageName = "CSharpStructureProvider";
    private HashSet<string>? _commonConstraintKeys;

    /// <summary>Gets the language name.</summary>
    public string Name => LanguageName;

    /// <summary>Gets the configuration type.</summary>
    public Type ConfigType => typeof(CSharpStructureProviderConfig);

    /// <summary>Gets the FHIR primitive type map (not used for this generator).</summary>
    public Dictionary<string, string> FhirPrimitiveTypeMap => new();

    /// <summary>Gets a value indicating whether this language is idempotent.</summary>
    public bool IsIdempotent => true;

    /// <summary>Exports the structure definition provider code.</summary>
    /// <param name="config">The configuration.</param>
    /// <param name="definitions">The definitions to export.</param>
    public void Export(object config, DefinitionCollection definitions)
    {
        if (config is not CSharpStructureProviderConfig providerConfig)
        {
            throw new ArgumentException($"Configuration must be of type {nameof(CSharpStructureProviderConfig)}", nameof(config));
        }

        // Get the FHIR version (use Stu3 to match FhirSpecification enum casing)
        string fhirVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "R4",
            FhirReleases.FhirSequenceCodes.R4B => "R4B",
            FhirReleases.FhirSequenceCodes.R5 => "R5",
            FhirReleases.FhirSequenceCodes.STU3 => "Stu3",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Create output directory if it doesn't exist
        string outputDir = Path.GetFullPath(providerConfig.OutputDirectory);
        Directory.CreateDirectory(outputDir);

        // Generate the provider class
        string outputPath = Path.Combine(outputDir, $"{fhirVersion}StructureDefinitionSummaryProvider.g.cs");
        string code = GenerateProviderCode(fhirVersion, definitions, providerConfig);

        File.WriteAllText(outputPath, code, Encoding.UTF8);

        Console.WriteLine($"Generated {outputPath}");

        // Generate the reference metadata class
        string refMetadataPath = Path.Combine(outputDir, $"{fhirVersion}ReferenceMetadata.g.cs");
        string refMetadataCode = GenerateReferenceMetadata(fhirVersion, definitions, providerConfig);

        File.WriteAllText(refMetadataPath, refMetadataCode, Encoding.UTF8);

        Console.WriteLine($"Generated {refMetadataPath}");
    }

    private string GenerateProviderCode(string fhirVersion, DefinitionCollection definitions, CSharpStructureProviderConfig config)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// <copyright file=\"" + $"{fhirVersion}StructureDefinitionSummaryProvider.g.cs" + "\" company=\"Microsoft Corporation\">");
        sb.AppendLine("//     Copyright (c) Microsoft Corporation. All rights reserved.");
        sb.AppendLine("//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.");
        sb.AppendLine("// </copyright>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using Ignixa.Domain;");
        sb.AppendLine("using Ignixa.SourceNodeSerialization;");
        sb.AppendLine("using Ignixa.SourceNodeSerialization.Abstractions;");
        sb.AppendLine("using Ignixa.SourceNodeSerialization.Specification;");
        sb.AppendLine("using Ignixa.Specification;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Pre-generated IStructureDefinitionSummaryProvider for FHIR {fhirVersion}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {fhirVersion}StructureDefinitionSummaryProvider : IStructureDefinitionSummaryProvider, IFhirSchemaProvider");
        sb.AppendLine("{");

        // Version property
        sb.AppendLine($"    public FhirSpecification Version => FhirSpecification.{fhirVersion};");
        sb.AppendLine();

        // Resource type names
        var resourceTypes = definitions.ResourcesByName.Keys
            .OrderBy(name => name)
            .ToList();

        sb.AppendLine("    public IReadOnlySet<string> ResourceTypeNames { get; } = new HashSet<string>");
        sb.AppendLine("    {");
        foreach (string resourceType in resourceTypes)
        {
            sb.AppendLine($"        \"{resourceType}\",");
        }
        sb.AppendLine("    }.ToImmutableHashSet();");
        sb.AppendLine();

        // IsKnownType method
        sb.AppendLine("    public bool IsKnownType(string type)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _types.ContainsKey(type);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Provide method with case-insensitive fallback for choice type support
        sb.AppendLine("    public IStructureDefinitionSummary? Provide(string canonical)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Handle full canonical URLs like \"http://hl7.org/fhir/StructureDefinition/Patient\"");
        sb.AppendLine("        // Extract the type name (last segment after the last '/')");
        sb.AppendLine("        string typeName = canonical;");
        sb.AppendLine("        if (canonical.Contains('/'))");
        sb.AppendLine("        {");
        sb.AppendLine("            typeName = canonical.Substring(canonical.LastIndexOf('/') + 1);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Try exact match first (most common case)");
        sb.AppendLine("        if (_types.TryGetValue(typeName, out var summary))");
        sb.AppendLine("            return summary;");
        sb.AppendLine();
        sb.AppendLine("        // For choice elements, the SDK extracts suffixes like 'Code' from 'valueCode'");
        sb.AppendLine("        // and tries to lookup the type. We need case-insensitive fallback.");
        sb.AppendLine("        // Primitive types are lowercase ('code', 'dateTime'), complex types are PascalCase.");
        sb.AppendLine("        foreach (var kvp in _types)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.Equals(kvp.Key, typeName, StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("                return kvp.Value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Pre-scan for common constraints (must happen before generating elements)
        CollectCommonConstraints(definitions);

        // Generate common constraints dictionary (optimization)
        GenerateCommonConstraintsDict(sb);

        // Generate types dictionary with lazy element initialization
        GenerateTypesDictionary(sb, definitions);

        // Generate nested implementation classes
        GenerateNestedClasses(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateTypesDictionary(StringBuilder sb, DefinitionCollection definitions)
    {
        sb.AppendLine("    private static readonly Dictionary<string, IStructureDefinitionSummary> _types = new()");
        sb.AppendLine("    {");

        // Collect all types (primitives, complex types, resources, AND BackboneElements)
        var allTypes = new List<(string Name, StructureDefinition SD, bool IsResource, string? BackbonePath)>();

        foreach (var kvp in definitions.PrimitiveTypesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, false, null));
        }

        foreach (var kvp in definitions.ComplexTypesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, false, null));
        }

        foreach (var kvp in definitions.ResourcesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, true, null));

            // Extract BackboneElement types from this resource
            var backboneElements = ExtractBackboneElements(kvp.Value);
            foreach (var (backboneName, backbonePath) in backboneElements)
            {
                // Add BackboneElement as a separate type with qualified name (e.g., "AuditEvent.Agent")
                allTypes.Add((backboneName, kvp.Value, false, backbonePath));
            }
        }

        // Sort alphabetically
        allTypes = allTypes.OrderBy(t => t.Name).ToList();

        foreach (var (name, sd, isResource, backbonePath) in allTypes)
        {
            bool isAbstract = sd.Abstract ?? false;

            sb.AppendLine($"        [\"{name}\"] = new GeneratedStructureDefinitionSummary(");
            sb.AppendLine($"            typeName: \"{name}\",");
            sb.AppendLine($"            isAbstract: {(isAbstract ? "true" : "false")},");
            sb.AppendLine($"            isResource: {(isResource ? "true" : "false")},");
            sb.AppendLine($"            elementsFactory: () => {GetSafeMethodName(name)}_Elements()");
            sb.AppendLine($"        ),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        // Generate element factory methods for each type
        foreach (var (name, sd, _, backbonePath) in allTypes)
        {
            GenerateElementsMethod(sb, name, sd, definitions, backbonePath);
        }
    }

    /// <summary>
    /// Extracts all BackboneElement paths from a structure definition.
    /// Returns qualified type names (e.g., "AuditEvent.Agent") and their element paths.
    /// </summary>
    private List<(string TypeName, string ElementPath)> ExtractBackboneElements(StructureDefinition sd)
    {
        var backboneElements = new List<(string TypeName, string ElementPath)>();

        // Get all elements (not just top-level) to find BackboneElements
        var allElements = sd.cgElements(topLevelOnly: false, includeRoot: false, skipSlices: true);

        foreach (var element in allElements)
        {
            // Check if this element is a BackboneElement type
            if (element.Type.Any(t => t.Code == "BackboneElement"))
            {
                // Element path is like "AuditEvent.agent" - we want "AuditEvent.Agent" as type name
                string elementPath = element.Path;

                // Convert path to type name: "AuditEvent.agent" → "AuditEvent.Agent"
                // Capitalize the last segment after the last dot
                int lastDotIndex = elementPath.LastIndexOf('.');
                if (lastDotIndex > 0)
                {
                    string baseName = elementPath.Substring(0, lastDotIndex);
                    string elementName = elementPath.Substring(lastDotIndex + 1);
                    string capitalizedElementName = CapitalizeFirstLetter(elementName);
                    string typeName = $"{baseName}.{capitalizedElementName}";

                    backboneElements.Add((typeName, elementPath));
                }
            }
        }

        return backboneElements;
    }

    private void GenerateElementsMethod(StringBuilder sb, string typeName, StructureDefinition sd, DefinitionCollection definitions, string? backbonePath = null)
    {
        string safeName = GetSafeMethodName(typeName);

        sb.AppendLine($"    private static IReadOnlyCollection<IElementDefinitionSummary> {safeName}_Elements()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new IElementDefinitionSummary[]");
        sb.AppendLine("        {");

        // Get all elements for this type
        // If backbonePath is provided, get elements for that BackboneElement path
        // Otherwise, get top-level elements for the resource/type
        var elements = backbonePath != null
            ? sd.cgElements(forBackbonePath: backbonePath, topLevelOnly: true, includeRoot: false, skipSlices: true).ToList()
            : sd.cgElements(topLevelOnly: true, includeRoot: false, skipSlices: true).ToList();

        int order = 0;
        foreach (var element in elements)
        {
            GenerateElementDefinition(sb, element, definitions, order, typeName);
            order++;
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void GenerateElementDefinition(StringBuilder sb, ElementDefinition element, DefinitionCollection definitions, int order, string resourceTypeName)
    {
        string elementName = element.cgName();
        bool isCollection = element.cgIsArray();
        bool isRequired = element.cgCardinalityMin() > 0;
        bool inSummary = element.IsSummary ?? false;
        bool isChoiceElement = element.Path.EndsWith("[x]", StringComparison.Ordinal);
        bool isModifier = element.IsModifier ?? false;

        // Strip [x] suffix from choice element names to match Firely SDK behavior
        // The SDK uses "effective" not "effective[x]" for the ElementName property
        if (isChoiceElement && elementName.EndsWith("[x]", StringComparison.Ordinal))
        {
            elementName = elementName.Substring(0, elementName.Length - 3);
        }

        // Determine if this element is a resource type
        bool isResource = element.Type.Any(t => definitions.ResourcesByName.ContainsKey(t.Code ?? string.Empty));

        // Get type names - normalize FHIRPath URLs to FHIR type names
        // Keep type names as-is (e.g., "dateTime", "code") - the SDK handles matching
        var typeNames = element.Type.Select(t => NormalizeFhirPathTypeUrl(t.Code ?? "Element")).ToList();
        string defaultTypeName = typeNames.FirstOrDefault() ?? "Element";

        // Determine XML representation
        string representation = DetermineXmlRepresentation(elementName, element);

        // Extract extended metadata
        var (referenceTargets, binding, constraints, slicing, fixedValue, patternValue, defaultValue, contentReference, min, max) =
            ExtractExtendedMetadata(element, definitions, resourceTypeName, defaultTypeName);

        sb.AppendLine($"            new GeneratedElementDefinitionSummary(");
        sb.AppendLine($"                elementName: \"{elementName}\",");
        sb.AppendLine($"                isCollection: {(isCollection ? "true" : "false")},");
        sb.AppendLine($"                isRequired: {(isRequired ? "true" : "false")},");
        sb.AppendLine($"                inSummary: {(inSummary ? "true" : "false")},");
        sb.AppendLine($"                isChoiceElement: {(isChoiceElement ? "true" : "false")},");
        sb.AppendLine($"                isResource: {(isResource ? "true" : "false")},");
        sb.AppendLine($"                isModifier: {(isModifier ? "true" : "false")},");

        // Generate type array
        if (typeNames.Count == 0)
        {
            sb.AppendLine($"                type: new[] {{ _types[\"Element\"] }},");
        }
        else if (typeNames.Count == 1)
        {
            string typeName = typeNames[0];
            sb.AppendLine($"                type: new[] {{ _types[\"{EscapeString(typeName)}\"] }},");
        }
        else
        {
            sb.AppendLine($"                type: new ITypeSerializationInfo[] {{");
            foreach (var typeName in typeNames)
            {
                sb.AppendLine($"                    _types[\"{EscapeString(typeName)}\"],");
            }
            sb.AppendLine($"                }},");
        }

        sb.AppendLine($"                defaultTypeName: \"{EscapeString(defaultTypeName)}\",");
        sb.AppendLine($"                nonDefaultNamespace: null,");
        sb.AppendLine($"                representation: {representation},");
        sb.AppendLine($"                order: {order},");

        // Extended metadata parameters
        sb.AppendLine($"                referenceTargets: {referenceTargets},");
        sb.AppendLine($"                binding: {binding},");
        sb.AppendLine($"                constraints: {constraints},");
        sb.AppendLine($"                slicing: {slicing},");
        sb.AppendLine($"                fixedValue: {fixedValue},");
        sb.AppendLine($"                patternValue: {patternValue},");
        sb.AppendLine($"                defaultValue: {defaultValue},");
        sb.AppendLine($"                contentReference: {contentReference},");
        sb.AppendLine($"                min: {min},");
        sb.AppendLine($"                max: {max}");
        sb.AppendLine($"            ),");
    }

    private (string referenceTargets, string binding, string constraints, string slicing, string fixedValue, string patternValue, string defaultValue, string contentReference, string min, string max)
        ExtractExtendedMetadata(ElementDefinition element, DefinitionCollection definitions, string resourceTypeName, string elementTypeName)
    {
        // 1. Reference Targets
        string referenceTargets = "null";
        var referenceType = element.Type.FirstOrDefault(t => t.Code == "Reference");
        if (referenceType?.TargetProfile != null && referenceType.TargetProfile.Any())
        {
            var targets = referenceType.TargetProfile
                .Select(url => url.Split('/').Last())
                .Where(t => !string.IsNullOrEmpty(t))
                .ToList();

            if (targets.Count > 0)
            {
                referenceTargets = $"new[] {{ {string.Join(", ", targets.Select(t => $"\"{EscapeString(t)}\""))} }}";
            }
        }

        // 2. Binding
        string binding = "null";
        if (element.Binding != null && !string.IsNullOrEmpty(element.Binding.ValueSet))
        {
            string strength = element.Binding.Strength?.ToString() ?? "Unknown";
            binding = $"new BindingMetadata(\"{EscapeString(element.Binding.ValueSet)}\", \"{strength}\")";
        }

        // 3. Constraints
        string constraints = "null";
        if (element.Constraint != null && element.Constraint.Any())
        {
            var constraintList = element.Constraint
                .Select(c =>
                {
                    string key = c.Key ?? "";
                    string escapedKey = EscapeString(key);

                    // Use helper method for common constraints (>100 occurrences)
                    // Use element's type for AppliesTo, not parent resource
                    // e.g., ext-1 on Account.extension (type=Extension) → AppliesTo=["Extension"]
                    if (_commonConstraintKeys != null && _commonConstraintKeys.Contains(key))
                    {
                        return $"C(\"{escapedKey}\", \"{EscapeString(elementTypeName)}\")";
                    }

                    // For uncommon constraints, generate inline
                    // Use element's type for AppliesTo, consistent with common constraints
                    string severityValue = c.Severity?.ToString() ?? "error";
                    string severity = severityValue.Equals("error", StringComparison.OrdinalIgnoreCase)
                        ? "ConstraintSeverity.Error"
                        : "ConstraintSeverity.Warning";
                    string human = EscapeString(c.Human ?? "");
                    string expression = EscapeString(c.Expression ?? "");
                    string xpath = string.IsNullOrEmpty(c.Xpath) ? "null" : $"\"{EscapeString(c.Xpath)}\"";

                    return $"new ConstraintDefinition {{ Key = \"{escapedKey}\", Severity = {severity}, Human = \"{human}\", Expression = \"{expression}\", Xpath = {xpath}, AppliesTo = new[] {{ \"{EscapeString(elementTypeName)}\" }} }}";
                })
                .ToList();

            if (constraintList.Count > 0)
            {
                constraints = $"new[] {{ {string.Join(", ", constraintList)} }}";
            }
        }

        // 4. Slicing
        string slicing = "null";
        if (element.Slicing != null)
        {
            var discriminators = element.Slicing.Discriminator?
                .Select(d => $"{d.Type}:{d.Path}")
                .ToArray() ?? Array.Empty<string>();

            string rules = element.Slicing.Rules?.ToString() ?? "Open";
            bool ordered = element.Slicing.Ordered ?? false;

            if (discriminators.Length > 0)
            {
                string discriminatorArray = $"new[] {{ {string.Join(", ", discriminators.Select(d => $"\"{EscapeString(d)}\""))} }}";
                slicing = $"new SlicingMetadata({discriminatorArray}, \"{rules}\", {(ordered ? "true" : "false")})";
            }
        }

        // 5. Fixed Value (serialize as JSON)
        string fixedValue = "null";
        if (element.Fixed != null)
        {
            string json = SerializeToJson(element.Fixed);
            if (!string.IsNullOrEmpty(json))
            {
                fixedValue = $"\"{EscapeString(json)}\"";
            }
        }

        // 6. Pattern Value (serialize as JSON)
        string patternValue = "null";
        if (element.Pattern != null)
        {
            string json = SerializeToJson(element.Pattern);
            if (!string.IsNullOrEmpty(json))
            {
                patternValue = $"\"{EscapeString(json)}\"";
            }
        }

        // 7. Default Value (serialize as JSON)
        string defaultValue = "null";
        if (element.DefaultValue != null)
        {
            string json = SerializeToJson(element.DefaultValue);
            if (!string.IsNullOrEmpty(json))
            {
                defaultValue = $"\"{EscapeString(json)}\"";
            }
        }

        // 8. Content Reference
        string contentReference = "null";
        if (!string.IsNullOrEmpty(element.ContentReference))
        {
            contentReference = $"\"{EscapeString(element.ContentReference)}\"";
        }

        // 9. Min/Max cardinality
        string min = element.Min.HasValue ? element.Min.Value.ToString() : "null";
        string max = !string.IsNullOrEmpty(element.Max) ? $"\"{EscapeString(element.Max)}\"" : "null";

        return (referenceTargets, binding, constraints, slicing, fixedValue, patternValue, defaultValue, contentReference, min, max);
    }

    private string SerializeToJson(DataType value)
    {
        try
        {
            // Use Firely SDK's JSON serializer
            var serializer = new Hl7.Fhir.Serialization.FhirJsonSerializer();
            return serializer.SerializeToString(value);
        }
        catch
        {
            // Fallback to simple string representation
            return value.ToString() ?? string.Empty;
        }
    }

    /// <summary>
    /// Normalizes FHIRPath system type URLs to FHIR primitive type names.
    /// FHIRPath URLs like "http://hl7.org/fhirpath/System.String" are mapped to "string".
    /// Non-URL type codes are returned as-is.
    /// </summary>
    private string NormalizeFhirPathTypeUrl(string typeCode)
    {
        // Map FHIRPath system type URLs to FHIR primitive type names
        return typeCode switch
        {
            "http://hl7.org/fhirpath/System.String" => "string",
            "http://hl7.org/fhirpath/System.Boolean" => "boolean",
            "http://hl7.org/fhirpath/System.Integer" => "integer",
            "http://hl7.org/fhirpath/System.Decimal" => "decimal",
            "http://hl7.org/fhirpath/System.DateTime" => "dateTime",
            "http://hl7.org/fhirpath/System.Date" => "date",
            "http://hl7.org/fhirpath/System.Time" => "time",
            "http://hl7.org/fhirpath/System.Quantity" => "Quantity",
            _ => typeCode // Return as-is if not a FHIRPath URL
        };
    }

    private string DetermineXmlRepresentation(string elementName, ElementDefinition element)
    {
        // Special cases
        if (elementName == "id" || elementName == "lang")
            return "XmlRepresentation.XmlAttr";

        if (elementName == "div" || elementName.Contains("html", StringComparison.OrdinalIgnoreCase))
            return "XmlRepresentation.XHtml";

        return "XmlRepresentation.XmlElement";
    }

    private void GenerateNestedClasses(StringBuilder sb)
    {
        // GeneratedStructureDefinitionSummary class
        sb.AppendLine("    private sealed class GeneratedStructureDefinitionSummary : IStructureDefinitionSummary, IStructureDefinitionReference");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly Func<IReadOnlyCollection<IElementDefinitionSummary>> _elementsFactory;");
        sb.AppendLine("        private IReadOnlyCollection<IElementDefinitionSummary>? _elements;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedStructureDefinitionSummary(");
        sb.AppendLine("            string typeName,");
        sb.AppendLine("            bool isAbstract,");
        sb.AppendLine("            bool isResource,");
        sb.AppendLine("            Func<IReadOnlyCollection<IElementDefinitionSummary>> elementsFactory)");
        sb.AppendLine("        {");
        sb.AppendLine("            TypeName = typeName;");
        sb.AppendLine("            IsAbstract = isAbstract;");
        sb.AppendLine("            IsResource = isResource;");
        sb.AppendLine("            _elementsFactory = elementsFactory;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public string TypeName { get; }");
        sb.AppendLine("        public bool IsAbstract { get; }");
        sb.AppendLine("        public bool IsResource { get; }");
        sb.AppendLine();
        sb.AppendLine("        // IStructureDefinitionReference implementation");
        sb.AppendLine("        // ReferredType returns the type name for choice type validation");
        sb.AppendLine("        public string ReferredType => TypeName;");
        sb.AppendLine();
        sb.AppendLine("        public IReadOnlyCollection<IElementDefinitionSummary> GetElements()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _elements ??= _elementsFactory();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GeneratedElementDefinitionSummary class with extended metadata
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extended element definition summary with additional metadata beyond IElementDefinitionSummary.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private sealed class GeneratedElementDefinitionSummary : IElementDefinitionSummary, IExtendedElementMetadata");
        sb.AppendLine("    {");
        sb.AppendLine("        public GeneratedElementDefinitionSummary(");
        sb.AppendLine("            string elementName,");
        sb.AppendLine("            bool isCollection,");
        sb.AppendLine("            bool isRequired,");
        sb.AppendLine("            bool inSummary,");
        sb.AppendLine("            bool isChoiceElement,");
        sb.AppendLine("            bool isResource,");
        sb.AppendLine("            bool isModifier,");
        sb.AppendLine("            ITypeSerializationInfo[] type,");
        sb.AppendLine("            string defaultTypeName,");
        sb.AppendLine("            string? nonDefaultNamespace,");
        sb.AppendLine("            XmlRepresentation representation,");
        sb.AppendLine("            int order,");
        sb.AppendLine("            string[]? referenceTargets = null,");
        sb.AppendLine("            BindingMetadata? binding = null,");
        sb.AppendLine("            ConstraintDefinition[]? constraints = null,");
        sb.AppendLine("            SlicingMetadata? slicing = null,");
        sb.AppendLine("            string? fixedValue = null,");
        sb.AppendLine("            string? patternValue = null,");
        sb.AppendLine("            string? defaultValue = null,");
        sb.AppendLine("            string? contentReference = null,");
        sb.AppendLine("            int? min = null,");
        sb.AppendLine("            string? max = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            ElementName = elementName;");
        sb.AppendLine("            IsCollection = isCollection;");
        sb.AppendLine("            IsRequired = isRequired;");
        sb.AppendLine("            InSummary = inSummary;");
        sb.AppendLine("            IsChoiceElement = isChoiceElement;");
        sb.AppendLine("            IsResource = isResource;");
        sb.AppendLine("            IsModifier = isModifier;");
        sb.AppendLine("            Type = type;");
        sb.AppendLine("            DefaultTypeName = defaultTypeName;");
        sb.AppendLine("            NonDefaultNamespace = nonDefaultNamespace;");
        sb.AppendLine("            Representation = representation;");
        sb.AppendLine("            Order = order;");
        sb.AppendLine("            ReferenceTargets = referenceTargets;");
        sb.AppendLine("            Binding = binding;");
        sb.AppendLine("            Constraints = constraints;");
        sb.AppendLine("            Slicing = slicing;");
        sb.AppendLine("            FixedValue = fixedValue;");
        sb.AppendLine("            PatternValue = patternValue;");
        sb.AppendLine("            DefaultValue = defaultValue;");
        sb.AppendLine("            ContentReference = contentReference;");
        sb.AppendLine("            Min = min;");
        sb.AppendLine("            Max = max;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // IElementDefinitionSummary properties");
        sb.AppendLine("        public string ElementName { get; }");
        sb.AppendLine("        public bool IsCollection { get; }");
        sb.AppendLine("        public bool IsRequired { get; }");
        sb.AppendLine("        public bool InSummary { get; }");
        sb.AppendLine("        public bool IsChoiceElement { get; }");
        sb.AppendLine("        public bool IsResource { get; }");
        sb.AppendLine("        public bool IsModifier { get; }");
        sb.AppendLine("        public ITypeSerializationInfo[] Type { get; }");
        sb.AppendLine("        public string DefaultTypeName { get; }");
        sb.AppendLine("        public string? NonDefaultNamespace { get; }");
        sb.AppendLine("        public XmlRepresentation Representation { get; }");
        sb.AppendLine("        public int Order { get; }");
        sb.AppendLine();
        sb.AppendLine("        // Extended metadata properties (IExtendedElementMetadata)");
        sb.AppendLine("        /// <summary>Valid target resource types for Reference elements.</summary>");
        sb.AppendLine("        public string[]? ReferenceTargets { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>ValueSet binding information.</summary>");
        sb.AppendLine("        public BindingMetadata? Binding { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>FHIRPath constraints (invariants).</summary>");
        sb.AppendLine("        public ConstraintDefinition[]? Constraints { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Slicing definition.</summary>");
        sb.AppendLine("        public SlicingMetadata? Slicing { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Fixed value (serialized as JSON string).</summary>");
        sb.AppendLine("        public string? FixedValue { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Pattern value (serialized as JSON string).</summary>");
        sb.AppendLine("        public string? PatternValue { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Default value (serialized as JSON string).</summary>");
        sb.AppendLine("        public string? DefaultValue { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Content reference (e.g., \"#Patient.contact\" for recursive structures).</summary>");
        sb.AppendLine("        public string? ContentReference { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Minimum cardinality.</summary>");
        sb.AppendLine("        public int? Min { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Maximum cardinality (\"*\" for unbounded).</summary>");
        sb.AppendLine("        public string? Max { get; }");
        sb.AppendLine("    }");
    }

    private string GetSafeMethodName(string typeName)
    {
        // Replace special characters to make valid C# method names
        return typeName.Replace("-", "_").Replace(".", "_").Replace("#", "Sharp");
    }

    private string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private string CapitalizeFirstLetter(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        if (char.IsUpper(value[0]))
            return value; // Already capitalized

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }

    private string GenerateReferenceMetadata(string fhirVersion, DefinitionCollection definitions, CSharpStructureProviderConfig config)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// <copyright file=\"" + $"{fhirVersion}ReferenceMetadata.g.cs" + "\" company=\"Microsoft Corporation\">");
        sb.AppendLine("//     Copyright (c) Microsoft Corporation. All rights reserved.");
        sb.AppendLine("//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.");
        sb.AppendLine("// </copyright>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Ignixa.SourceNodeSerialization.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Pre-generated reference metadata for FHIR {fhirVersion}.");
        sb.AppendLine("/// Provides efficient lookup of which elements are references and their target types.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {fhirVersion}ReferenceMetadata");
        sb.AppendLine("{");

        // Generate metadata dictionary
        sb.AppendLine("    private static readonly Dictionary<string, List<ReferenceFieldMetadata>> _metadata = new()");
        sb.AppendLine("    {");

        // Process all resources
        var resources = definitions.ResourcesByName.OrderBy(kvp => kvp.Key).ToList();

        foreach (var (resourceName, sd) in resources)
        {
            var referenceElements = sd.cgElements(topLevelOnly: true, includeRoot: false, skipSlices: true)
                .Where(e => e.Type.Any(t => t.Code == "Reference"))
                .ToList();

            if (referenceElements.Count == 0)
                continue;

            sb.AppendLine($"        [\"{resourceName}\"] = new List<ReferenceFieldMetadata>");
            sb.AppendLine($"        {{");

            foreach (var element in referenceElements)
            {
                string elementName = element.cgName();
                int min = element.cgCardinalityMin();
                string max = element.Max ?? "*";
                bool inSummary = element.IsSummary ?? false;

                // Extract target profiles
                var referenceType = element.Type.FirstOrDefault(t => t.Code == "Reference");
                var targetProfiles = new List<string>();

                if (referenceType?.TargetProfile != null && referenceType.TargetProfile.Any())
                {
                    foreach (var targetUrl in referenceType.TargetProfile)
                    {
                        // Extract resource name from URL like "http://hl7.org/fhir/StructureDefinition/Patient"
                        string resourceType = targetUrl.Split('/').Last();
                        targetProfiles.Add(resourceType);
                    }
                }

                // Generate field metadata (positional parameters for record)
                string targetTypesArray;
                if (targetProfiles.Count > 0)
                {
                    targetTypesArray = $"new[] {{ {string.Join(", ", targetProfiles.Select(t => $"\"{t}\""))} }}";
                }
                else
                {
                    targetTypesArray = "System.Array.Empty<string>()";
                }

                sb.AppendLine($"            new ReferenceFieldMetadata(\"{elementName}\", {min}, \"{max}\", {targetTypesArray}, {(inSummary ? "true" : "false")}),");
            }

            sb.AppendLine($"        }},");
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        // Generate lookup method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets reference metadata for a resource type.");
        sb.AppendLine("    /// Returns empty list if resource type has no references or is unknown.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [System.CLSCompliant(false)]");
        sb.AppendLine("    public static IReadOnlyList<ReferenceFieldMetadata> GetMetadata(string resourceType)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _metadata.TryGetValue(resourceType, out var metadata)");
        sb.AppendLine("            ? metadata");
        sb.AppendLine("            : System.Array.Empty<ReferenceFieldMetadata>();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate HasReferences method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Checks if a resource type has any reference elements.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static bool HasReferences(string resourceType)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _metadata.ContainsKey(resourceType);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private Dictionary<string, (ElementDefinition.ConstraintComponent Constraint, int Count)>? _constraintData;

    private void CollectCommonConstraints(DefinitionCollection definitions)
    {
        // Collect all constraints across all types and count their frequency
        _constraintData = new Dictionary<string, (ElementDefinition.ConstraintComponent Constraint, int Count)>();

        foreach (var sd in definitions.ResourcesByName.Values
            .Concat(definitions.ComplexTypesByName.Values)
            .Concat(definitions.PrimitiveTypesByName.Values))
        {
            if (sd.Snapshot?.Element == null)
            {
                continue;
            }

            foreach (var element in sd.Snapshot.Element)
            {
                if (element.Constraint == null || !element.Constraint.Any())
                {
                    continue;
                }

                foreach (var constraint in element.Constraint)
                {
                    string key = constraint.Key ?? "";
                    if (string.IsNullOrEmpty(key))
                    {
                        continue;
                    }

                    if (!_constraintData.ContainsKey(key))
                    {
                        _constraintData[key] = (constraint, 1);
                    }
                    else
                    {
                        _constraintData[key] = (constraint, _constraintData[key].Count + 1);
                    }
                }
            }
        }

        // Only consider constraints that appear >100 times as "common"
        _commonConstraintKeys = new HashSet<string>(
            _constraintData
                .Where(kvp => kvp.Value.Count > 100)
                .Select(kvp => kvp.Key));
    }

    private void GenerateCommonConstraintsDict(StringBuilder sb)
    {
        if (_constraintData == null || _commonConstraintKeys == null || _commonConstraintKeys.Count == 0)
        {
            return;
        }

        var commonConstraints = _constraintData
            .Where(kvp => _commonConstraintKeys.Contains(kvp.Key))
            .OrderByDescending(kvp => kvp.Value.Count)
            .ToList();

        sb.AppendLine("    // Common constraints dictionary (frequency-optimized)");
        sb.AppendLine("    // These constraints appear >100 times and are shared to reduce code duplication");
        sb.AppendLine("    private static readonly Dictionary<string, ConstraintDefinition> _commonConstraints = new()");
        sb.AppendLine("    {");

        foreach (var (key, (constraint, count)) in commonConstraints)
        {
            string severityValue = constraint.Severity?.ToString() ?? "error";
            string severity = severityValue.Equals("error", StringComparison.OrdinalIgnoreCase)
                ? "ConstraintSeverity.Error"
                : "ConstraintSeverity.Warning";
            string human = EscapeString(constraint.Human ?? "");
            string expression = EscapeString(constraint.Expression ?? "");
            string xpath = string.IsNullOrEmpty(constraint.Xpath) ? "null" : $"\"{EscapeString(constraint.Xpath)}\"";

            sb.AppendLine($"        [\"{EscapeString(key)}\"] = new ConstraintDefinition");
            sb.AppendLine("        {");
            sb.AppendLine($"            Key = \"{EscapeString(key)}\",");
            sb.AppendLine($"            Severity = {severity},");
            sb.AppendLine($"            Human = \"{human}\",");
            sb.AppendLine($"            Expression = \"{expression}\",");
            sb.AppendLine($"            Xpath = {xpath},");
            sb.AppendLine("            AppliesTo = Array.Empty<string>()");
            sb.AppendLine($"        }}, // Used {count} times");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    // Helper method to create constraint with specific AppliesTo");
        sb.AppendLine("    private static ConstraintDefinition C(string key, string resourceType) =>");
        sb.AppendLine("        _commonConstraints[key] with { AppliesTo = new[] { resourceType } };");
        sb.AppendLine();
    }
}

/// <summary>
/// Configuration for the C# Structure Provider generator.
/// </summary>
public sealed class CSharpStructureProviderConfig
{
    /// <summary>Gets or sets the output directory for generated files.</summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>Gets or sets the namespace for generated classes.</summary>
    public string Namespace { get; set; } = "Sparky.Specification.Generated";
}
