// <copyright file="CSharpSearchParameterLanguage.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

using System.Text;
using System.Text.Json;
using Hl7.Fhir.Model;
using Microsoft.Health.Fhir.CodeGen.Language;
using Microsoft.Health.Fhir.CodeGen.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Packaging;

namespace Ignixa.Specification.Generators;

/// <summary>
/// Custom ILanguage implementation for generating C# SearchParameterInfo arrays from FHIR SearchParameter definitions.
/// Generates code-generated search parameter definitions to eliminate runtime JSON parsing overhead.
/// </summary>
public sealed class CSharpSearchParameterLanguage : ILanguage
{
    private const string LanguageName = "CSharpSearchParameter";

    /// <summary>Gets the language name.</summary>
    public string Name => LanguageName;

    /// <summary>Gets the configuration type.</summary>
    public Type ConfigType => typeof(CSharpSearchParameterConfig);

    /// <summary>Gets the FHIR primitive type map (not used for this generator).</summary>
    public Dictionary<string, string> FhirPrimitiveTypeMap => new();

    /// <summary>Gets a value indicating whether this language is idempotent.</summary>
    public bool IsIdempotent => true;

    /// <summary>Exports the search parameter definitions code.</summary>
    /// <param name="config">The configuration.</param>
    /// <param name="definitions">The definitions to export.</param>
    public void Export(object config, DefinitionCollection definitions)
    {
        if (config is not CSharpSearchParameterConfig paramConfig)
        {
            throw new ArgumentException($"Configuration must be of type {nameof(CSharpSearchParameterConfig)}", nameof(config));
        }

        // Get the FHIR version
        string fhirVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "R4",
            FhirReleases.FhirSequenceCodes.R4B => "R4B",
            FhirReleases.FhirSequenceCodes.R5 => "R5",
            FhirReleases.FhirSequenceCodes.STU3 => "STU3",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Create output directory if it doesn't exist
        string outputDir = Path.GetFullPath(paramConfig.OutputDirectory);
        Directory.CreateDirectory(outputDir);

        // Generate the search parameter definitions class
        string outputPath = Path.Combine(outputDir, $"{fhirVersion}SearchParameterDefinitions.g.cs");
        string code = GenerateSearchParameterCode(fhirVersion, definitions, paramConfig);

        File.WriteAllText(outputPath, code, Encoding.UTF8);

        Console.WriteLine($"Generated {outputPath}");
    }

    private string GenerateSearchParameterCode(string fhirVersion, DefinitionCollection definitions, CSharpSearchParameterConfig config)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// <copyright file=\"" + $"{fhirVersion}SearchParameterDefinitions.g.cs" + "\" company=\"Microsoft Corporation\">");
        sb.AppendLine("//     Copyright (c) Microsoft Corporation. All rights reserved.");
        sb.AppendLine("//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.");
        sb.AppendLine("// </copyright>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Ignixa.Specification.ValueSets.Normative;");
        sb.AppendLine("using Ignixa.Search.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Pre-generated SearchParameterInfo array for FHIR {fhirVersion}.");
        sb.AppendLine("/// Eliminates runtime JSON parsing overhead (~50-200ms cold start → <5ms).");
        sb.AppendLine("/// Base FHIR search parameters only - custom tenant parameters loaded at runtime.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {fhirVersion}SearchParameterDefinitions");
        sb.AppendLine("{");
        sb.AppendLine("    private static SearchParameterInfo[]? _cached;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets all base FHIR {fhirVersion} search parameters.");
        sb.AppendLine("    /// Thread-safe lazy initialization with caching.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static SearchParameterInfo[] GetBaseSearchParameters()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_cached != null)");
        sb.AppendLine("            return _cached;");
        sb.AppendLine();
        sb.AppendLine("        // Lazy initialization - build array on first access");
        sb.AppendLine("        var parameters = new SearchParameterInfo[]");
        sb.AppendLine("        {");

        // Generate SearchParameterInfo entries from DefinitionCollection
        GenerateSearchParameterEntries(sb, definitions, fhirVersion);

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        _cached = parameters;");
        sb.AppendLine("        return parameters;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateSearchParameterEntries(StringBuilder sb, DefinitionCollection definitions, string fhirVersion)
    {
        // Parse the embedded search-parameters.json file from the Sparky.Search project
        // This is the same JSON file that SearchParameterDefinitionBuilder.ReadEmbeddedSearchParameters() loads at runtime
        string searchParamsPath = GetSearchParametersJsonPath(fhirVersion);

        if (!File.Exists(searchParamsPath))
        {
            sb.AppendLine($"            // ERROR: Search parameters file not found: {searchParamsPath}");
            sb.AppendLine($"            // Generate from FHIR package or ensure embedded JSON exists");
            return;
        }

        // Parse JSON bundle
        string json = File.ReadAllText(searchParamsPath);
        using JsonDocument doc = JsonDocument.Parse(json);

        if (!doc.RootElement.TryGetProperty("entry", out JsonElement entries))
        {
            sb.AppendLine($"            // ERROR: 'entry' array not found in search parameters bundle");
            return;
        }

        // Generate SearchParameterInfo for each entry
        int count = 0;
        foreach (JsonElement entry in entries.EnumerateArray())
        {
            if (!entry.TryGetProperty("resource", out JsonElement resource))
                continue;

            if (!resource.TryGetProperty("resourceType", out JsonElement resourceType) ||
                resourceType.GetString() != "SearchParameter")
                continue;

            GenerateSearchParameterInfoFromJson(sb, resource, count == 0);
            count++;
        }

        // Add hardcoded system parameter: _type
        // This parameter is used to search by resource type and is available for all resources
        // Not included in the standard FHIR search-parameters.json, but required by the spec
        sb.AppendLine(",");
        sb.AppendLine("            new SearchParameterInfo(");
        sb.AppendLine("                name: \"_type\",");
        sb.AppendLine("                code: \"_type\",");
        sb.AppendLine("                searchParamType: SearchParamType.Token,");
        sb.AppendLine("                url: new Uri(\"http://hl7.org/fhir/SearchParameter/Resource-type\"),");
        sb.AppendLine("                components: null,");
        sb.AppendLine("                expression: null,");
        sb.AppendLine("                targetResourceTypes: null,");
        sb.AppendLine("                baseResourceTypes: new[] { \"Resource\" },");
        sb.AppendLine("                description: \"Search for resources by resource type\")");
        count++;

        Console.WriteLine($"Generated {count} search parameters for {fhirVersion} (includes hardcoded _type)");
    }

    private string GetSearchParametersJsonPath(string fhirVersion)
    {
        // Resolve path to embedded search-parameters.json in Sparky.Search project
        // Assumes we're running from codegen/ directory
        string baseDir = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", "src", "Sparky.Search", "Data"));

        string versionDir = fhirVersion switch
        {
            "R4" => "R4",
            "R4B" => "R4B",
            "R5" => "R5",
            "STU3" => "Stu3",
            _ => throw new ArgumentException($"Unknown FHIR version: {fhirVersion}")
        };

        return Path.Combine(baseDir, versionDir, "search-parameters.json");
    }

    private void GenerateSearchParameterInfoFromJson(StringBuilder sb, JsonElement resource, bool isFirst)
    {
        if (!isFirst)
        {
            sb.AppendLine(",");
        }

        // Extract properties from SearchParameter JSON
        string? url = resource.TryGetProperty("url", out var urlProp) ? urlProp.GetString() : null;
        string? name = resource.TryGetProperty("name", out var nameProp) ? nameProp.GetString() : null;
        string? code = resource.TryGetProperty("code", out var codeProp) ? codeProp.GetString() : null;
        string? type = resource.TryGetProperty("type", out var typeProp) ? typeProp.GetString() : null;
        string? expression = resource.TryGetProperty("expression", out var exprProp) ? exprProp.GetString() : null;

        // Extract base (array of resource types)
        var baseTypes = new List<string>();
        if (resource.TryGetProperty("base", out var baseProp) && baseProp.ValueKind == JsonValueKind.Array)
        {
            foreach (var baseType in baseProp.EnumerateArray())
            {
                string? baseStr = baseType.GetString();
                if (!string.IsNullOrEmpty(baseStr))
                    baseTypes.Add(baseStr);
            }
        }

        // Extract target (array of target resource types for Reference parameters)
        var targetTypes = new List<string>();
        if (resource.TryGetProperty("target", out var targetProp) && targetProp.ValueKind == JsonValueKind.Array)
        {
            foreach (var targetType in targetProp.EnumerateArray())
            {
                string? targetStr = targetType.GetString();
                if (!string.IsNullOrEmpty(targetStr))
                    targetTypes.Add(targetStr);
            }
        }

        // Extract component (for composite search parameters)
        var components = new List<(string definition, string expression)>();
        if (resource.TryGetProperty("component", out var componentProp) && componentProp.ValueKind == JsonValueKind.Array)
        {
            foreach (var comp in componentProp.EnumerateArray())
            {
                // STU3 format: "definition": {"reference": "url"}
                // R4+ format: "definition": "url"
                string? def = null;
                if (comp.TryGetProperty("definition", out var defProp))
                {
                    if (defProp.ValueKind == JsonValueKind.String)
                    {
                        def = defProp.GetString();
                    }
                    else if (defProp.ValueKind == JsonValueKind.Object && defProp.TryGetProperty("reference", out var refProp))
                    {
                        def = refProp.GetString();
                    }
                }

                string? expr = comp.TryGetProperty("expression", out var exprProp2) ? exprProp2.GetString() : null;

                if (!string.IsNullOrEmpty(def))
                    components.Add((def!, expr ?? ""));
            }
        }

        // Generate SearchParameterInfo constructor call
        // Constructor signature: (name, code, searchParamType, url, components, expression, targetResourceTypes, baseResourceTypes, description)
        sb.Append("            new SearchParameterInfo(");
        sb.AppendLine();
        sb.AppendLine($"                name: {FormatStringLiteral(name)},");
        sb.AppendLine($"                code: {FormatStringLiteral(code)},");
        sb.AppendLine($"                searchParamType: SearchParamType.{CapitalizeFirstLetter(type ?? "String")},");
        sb.AppendLine($"                url: {FormatUriOrNull(url)},");
        sb.AppendLine($"                components: {FormatComponentArrayOrNull(components)},");
        sb.AppendLine($"                expression: {FormatStringLiteral(expression)},");
        sb.AppendLine($"                targetResourceTypes: {FormatStringArrayOrNull(targetTypes)},");
        sb.AppendLine($"                baseResourceTypes: {FormatStringArrayOrNull(baseTypes)},");
        sb.AppendLine($"                description: null)");
    }

    private string FormatStringLiteral(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return "null";

        return $"\"{EscapeString(value)}\"";
    }

    private string FormatUriOrNull(string? url)
    {
        if (string.IsNullOrEmpty(url))
            return "null";

        return $"new Uri(\"{EscapeString(url)}\")";
    }

    private string FormatStringArray(List<string> values)
    {
        if (values.Count == 0)
            return "Array.Empty<string>()";

        var items = values.Select(v => $"\"{EscapeString(v)}\"");
        return $"new[] {{ {string.Join(", ", items)} }}";
    }

    private string FormatStringArrayOrNull(List<string> values)
    {
        if (values.Count == 0)
            return "null";

        return FormatStringArray(values);
    }

    private string FormatComponentArrayOrNull(List<(string definition, string expression)> components)
    {
        if (components.Count == 0)
            return "null";

        var items = components.Select(c =>
            $"new SearchParameterComponentInfo(new Uri(\"{EscapeString(c.definition)}\"), {FormatStringLiteral(c.expression)})");

        return $"new[] {{ {string.Join(", ", items)} }}";
    }

    private string CapitalizeFirstLetter(string value)
    {
        if (string.IsNullOrEmpty(value))
            return "String";

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }

    private string EscapeString(string value)
    {
        if (value == null)
            return "null";

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }
}

/// <summary>
/// Configuration for the C# Search Parameter generator.
/// </summary>
public sealed class CSharpSearchParameterConfig
{
    /// <summary>Gets or sets the output directory for generated files.</summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>Gets or sets the namespace for generated classes.</summary>
    public string Namespace { get; set; } = "Sparky.Specification.Generated";
}
