// <copyright file="CSharpCodeSystemResolverLanguage.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

using System.Text;
using System.Text.Json;
using Microsoft.Health.Fhir.CodeGen.Language;
using Microsoft.Health.Fhir.CodeGen.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Packaging;

namespace Ignixa.Specification.Generators;

/// <summary>
/// Custom ILanguage implementation for generating C# CodeSystemResolver mappings.
/// Generates code-generated resource path → code system mappings to eliminate runtime JSON parsing overhead.
/// </summary>
public sealed class CSharpCodeSystemResolverLanguage : ILanguage
{
    private const string LanguageName = "CSharpCodeSystemResolver";

    /// <summary>Gets the language name.</summary>
    public string Name => LanguageName;

    /// <summary>Gets the configuration type.</summary>
    public Type ConfigType => typeof(CSharpCodeSystemResolverConfig);

    /// <summary>Gets the FHIR primitive type map (not used for this generator).</summary>
    public Dictionary<string, string> FhirPrimitiveTypeMap => new();

    /// <summary>Gets a value indicating whether this language is idempotent.</summary>
    public bool IsIdempotent => true;

    /// <summary>Exports the code system resolver mappings code.</summary>
    /// <param name="config">The configuration.</param>
    /// <param name="definitions">The definitions to export.</param>
    public void Export(object config, DefinitionCollection definitions)
    {
        if (config is not CSharpCodeSystemResolverConfig resolverConfig)
        {
            throw new ArgumentException($"Configuration must be of type {nameof(CSharpCodeSystemResolverConfig)}", nameof(config));
        }

        // Get the FHIR version
        string fhirVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "R4",
            FhirReleases.FhirSequenceCodes.R4B => "R4B",
            FhirReleases.FhirSequenceCodes.R5 => "R5",
            FhirReleases.FhirSequenceCodes.R6 => "R6",
            FhirReleases.FhirSequenceCodes.STU3 => "STU3",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Create output directory if it doesn't exist
        string outputDir = Path.GetFullPath(resolverConfig.OutputDirectory);
        Directory.CreateDirectory(outputDir);

        // Generate the code system resolver class
        string outputPath = Path.Combine(outputDir, $"{fhirVersion}CodeSystemMappings.g.cs");
        string code = GenerateCodeSystemResolverCode(fhirVersion, definitions, resolverConfig);

        File.WriteAllText(outputPath, code, Encoding.UTF8);

        Console.WriteLine($"Generated {outputPath}");
    }

    private string GenerateCodeSystemResolverCode(string fhirVersion, DefinitionCollection definitions, CSharpCodeSystemResolverConfig config)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// <copyright file=\"" + $"{fhirVersion}CodeSystemMappings.g.cs" + "\" company=\"Microsoft Corporation\">");
        sb.AppendLine("//     Copyright (c) Microsoft Corporation. All rights reserved.");
        sb.AppendLine("//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.");
        sb.AppendLine("// </copyright>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Pre-generated code system mappings for FHIR {fhirVersion}.");
        sb.AppendLine("/// Maps resource paths to their canonical code system URLs.");
        sb.AppendLine("/// Eliminates runtime JSON parsing overhead.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {fhirVersion}CodeSystemMappings");
        sb.AppendLine("{");
        sb.AppendLine("    private static Dictionary<string, string>? _cached;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets all resource path → code system URL mappings for FHIR {fhirVersion}.");
        sb.AppendLine("    /// Thread-safe lazy initialization with caching.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Dictionary<string, string> GetMappings()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_cached != null)");
        sb.AppendLine("            return _cached;");
        sb.AppendLine();
        sb.AppendLine("        var mappings = new Dictionary<string, string>");
        sb.AppendLine("        {");

        // Generate mappings from FHIR package metadata
        GenerateCodeSystemMappings(sb, definitions, fhirVersion);

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        _cached = mappings;");
        sb.AppendLine("        return mappings;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateCodeSystemMappings(StringBuilder sb, DefinitionCollection definitions, string fhirVersion)
    {
        // Extract resource path → code system mappings from FHIR package metadata
        // by analyzing element definitions and their value set bindings
        var mappings = new SortedDictionary<string, string>();

        // First, try to load from static JSON file if it exists
        string mappingsPath = GetCodeSystemMappingsJsonPath(fhirVersion);
        if (File.Exists(mappingsPath))
        {
            try
            {
                string json = File.ReadAllText(mappingsPath, Encoding.UTF8);
                JsonDocument.Parse(json).Dispose();

                using JsonDocument doc = JsonDocument.Parse(json);
                foreach (JsonProperty property in doc.RootElement.EnumerateObject())
                {
                    string path = property.Name;
                    string? codeSystem = property.Value.GetString();
                    if (!string.IsNullOrEmpty(codeSystem))
                    {
                        mappings[path] = codeSystem;
                    }
                }
            }
            catch
            {
                // Fall back to UTF-16
                try
                {
                    string json = File.ReadAllText(mappingsPath, Encoding.Unicode);
                    using JsonDocument doc = JsonDocument.Parse(json);
                    foreach (JsonProperty property in doc.RootElement.EnumerateObject())
                    {
                        string path = property.Name;
                        string? codeSystem = property.Value.GetString();
                        if (!string.IsNullOrEmpty(codeSystem))
                        {
                            mappings[path] = codeSystem;
                        }
                    }
                }
                catch
                {
                    // Continue if JSON parsing fails
                }
            }
        }

        // Additionally, extract mappings from FHIR package metadata
        // by analyzing resources and their element bindings
        if (definitions.ResourcesByName != null)
        {
            foreach (var (resourceName, resource) in definitions.ResourcesByName)
            {
                ExtractCodeSystemMappingsFromResource(mappings, resource, resourceName);
            }
        }

        int count = 0;
        foreach (var (path, codeSystem) in mappings)
        {
            if (count > 0)
                sb.AppendLine(",");

            sb.Append($"            {{ \"{EscapeString(path)}\", \"{EscapeString(codeSystem)}\" }}");
            count++;
        }

        if (count > 0)
            sb.AppendLine();

        Console.WriteLine($"Generated {count} code system mappings for {fhirVersion}");
    }

    private void ExtractCodeSystemMappingsFromResource(SortedDictionary<string, string> mappings, Hl7.Fhir.Model.StructureDefinition resource, string resourceName)
    {
        // Extract code system bindings from element definitions
        if (resource.Snapshot?.Element == null)
            return;

        foreach (var element in resource.Snapshot.Element)
        {
            if (element.Binding?.ValueSet == null)
                continue;

            string path = element.Path ?? string.Empty;
            if (string.IsNullOrEmpty(path))
                continue;

            // Remove [x] suffix from choice type elements
            path = path.Replace("[x]", string.Empty);

            string? valueSetUrl = element.Binding.ValueSet;
            if (string.IsNullOrEmpty(valueSetUrl))
                continue;

            // Try to extract the underlying code system from the value set
            string? codeSystemUrl = ExtractCodeSystemFromValueSet(valueSetUrl, mappings.Values);
            if (string.IsNullOrEmpty(codeSystemUrl))
            {
                codeSystemUrl = valueSetUrl; // Fall back to value set if code system not found
            }

            // Remove canonical version suffix (|version)
            if (codeSystemUrl.Contains("|"))
            {
                codeSystemUrl = codeSystemUrl.Substring(0, codeSystemUrl.IndexOf("|"));
            }

            // Add mapping from path to code system URL
            if (!mappings.ContainsKey(path))
            {
                mappings[path] = codeSystemUrl;
            }
        }
    }

    private string? ExtractCodeSystemFromValueSet(string valueSetUrl, ICollection<string> existingMappings)
    {
        // Try to extract the primary code system from a value set URL
        // For common FHIR value sets, use known code system mappings

        // Map common FHIR value sets to their primary code systems
        var knownMappings = new Dictionary<string, string>
        {
            { "http://hl7.org/fhir/ValueSet/languages", "urn:ietf:bcp:47" },
            { "http://hl7.org/fhir/ValueSet/mimetypes", "urn:ietf:bcp:13" },
            { "http://hl7.org/fhir/ValueSet/currencies", "urn:iso:std:iso:4217" },
            { "http://hl7.org/fhir/ValueSet/country", "urn:iso:std:iso:3166" },
            { "http://hl7.org/fhir/ValueSet/language", "urn:ietf:bcp:47" },
        };

        if (knownMappings.TryGetValue(valueSetUrl, out var codeSystem))
        {
            return codeSystem;
        }

        // For HL7 value sets, try to extract the code system from the URL pattern
        if (valueSetUrl.StartsWith("http://hl7.org/fhir/ValueSet/"))
        {
            string valueSetName = valueSetUrl.Substring("http://hl7.org/fhir/ValueSet/".Length);
            // Many HL7 value sets map to code systems with similar names
            // For example: ValueSet/administrative-gender → CodeSystem/administrative-gender
            string possibleCodeSystemUrl = $"http://hl7.org/fhir/CodeSystem/{valueSetName}";
            // We could validate this exists, but for now assume the pattern holds
            return possibleCodeSystemUrl;
        }

        return null;
    }

    private string GetCodeSystemMappingsJsonPath(string fhirVersion)
    {
        // Resolve path to embedded resourcepath-codesystem-mappings.json in Ignixa.Search project
        string baseDir = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "../../src", "Ignixa.Search", "Data"));

        string versionDir = fhirVersion switch
        {
            "R4" => "R4",
            "R4B" => "R4B",
            "R5" => "R5",
            "R6" => "R6",
            "STU3" => "Stu3",
            _ => throw new ArgumentException($"Unknown FHIR version: {fhirVersion}")
        };

        return Path.Combine(baseDir, versionDir, "resourcepath-codesystem-mappings.json");
    }

    private string EscapeString(string value)
    {
        if (value == null)
            return "null";

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }
}

/// <summary>
/// Configuration for the C# CodeSystemResolver generator.
/// </summary>
public sealed class CSharpCodeSystemResolverConfig
{
    /// <summary>Gets or sets the output directory for generated files.</summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>Gets or sets the namespace for generated classes.</summary>
    public string Namespace { get; set; } = "Sparky.Search.Generated";
}
