// <copyright file="CSharpCompartmentLanguage.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

using System.Text;
using System.Text.Json;
using Microsoft.Health.Fhir.CodeGen.Language;
using Microsoft.Health.Fhir.CodeGen.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Packaging;

namespace Ignixa.Specification.Generators;

/// <summary>
/// Custom ILanguage implementation for generating C# Compartment definitions from FHIR CompartmentDefinition resources.
/// Generates code-generated compartment definitions to eliminate runtime JSON parsing overhead.
/// </summary>
public sealed class CSharpCompartmentLanguage : ILanguage
{
    private const string LanguageName = "CSharpCompartment";

    /// <summary>Gets the language name.</summary>
    public string Name => LanguageName;

    /// <summary>Gets the configuration type.</summary>
    public Type ConfigType => typeof(CSharpCompartmentConfig);

    /// <summary>Gets the FHIR primitive type map (not used for this generator).</summary>
    public Dictionary<string, string> FhirPrimitiveTypeMap => new();

    /// <summary>Gets a value indicating whether this language is idempotent.</summary>
    public bool IsIdempotent => true;

    /// <summary>Exports the compartment definitions code.</summary>
    /// <param name="config">The configuration.</param>
    /// <param name="definitions">The definitions to export.</param>
    public void Export(object config, DefinitionCollection definitions)
    {
        if (config is not CSharpCompartmentConfig compartmentConfig)
        {
            throw new ArgumentException($"Configuration must be of type {nameof(CSharpCompartmentConfig)}", nameof(config));
        }

        // Get the FHIR version
        string fhirVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "R4",
            FhirReleases.FhirSequenceCodes.R4B => "R4B",
            FhirReleases.FhirSequenceCodes.R5 => "R5",
            FhirReleases.FhirSequenceCodes.R6 => "R6",
            FhirReleases.FhirSequenceCodes.STU3 => "STU3",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Create output directory if it doesn't exist
        string outputDir = Path.GetFullPath(compartmentConfig.OutputDirectory);
        Directory.CreateDirectory(outputDir);

        // Generate the compartment definitions class
        string outputPath = Path.Combine(outputDir, $"{fhirVersion}CompartmentDefinitions.g.cs");
        string code = GenerateCompartmentCode(fhirVersion, definitions, compartmentConfig);

        File.WriteAllText(outputPath, code, Encoding.UTF8);

        Console.WriteLine($"Generated {outputPath}");
    }

    private string GenerateCompartmentCode(string fhirVersion, DefinitionCollection definitions, CSharpCompartmentConfig config)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// <copyright file=\"" + $"{fhirVersion}CompartmentDefinitions.g.cs" + "\" company=\"Microsoft Corporation\">");
        sb.AppendLine("//     Copyright (c) Microsoft Corporation. All rights reserved.");
        sb.AppendLine("//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.");
        sb.AppendLine("// </copyright>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Ignixa.Specification.ValueSets.Normative;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Pre-generated Compartment definitions for FHIR {fhirVersion}.");
        sb.AppendLine("/// Eliminates runtime JSON parsing overhead.");
        sb.AppendLine("/// Thread-safe lazy initialization with caching.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {fhirVersion}CompartmentDefinitions");
        sb.AppendLine("{");
        sb.AppendLine("    private static Dictionary<CompartmentType, (CompartmentType Code, Uri Url, IList<(string Resource, IList<string> Params)> Resources)>? _cached;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets all compartment definitions for FHIR {fhirVersion}.");
        sb.AppendLine("    /// Thread-safe lazy initialization with caching.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Dictionary<CompartmentType, (CompartmentType Code, Uri Url, IList<(string Resource, IList<string> Params)> Resources)> GetCompartments()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_cached != null)");
        sb.AppendLine("            return _cached;");
        sb.AppendLine();
        sb.AppendLine("        var compartments = new Dictionary<CompartmentType, (CompartmentType Code, Uri Url, IList<(string Resource, IList<string> Params)> Resources)>");
        sb.AppendLine("        {");

        // Generate compartment entries from FHIR package metadata
        GenerateCompartmentEntries(sb, definitions, fhirVersion);

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        _cached = compartments;");
        sb.AppendLine("        return _cached;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateCompartmentEntries(StringBuilder sb, DefinitionCollection definitions, string fhirVersion)
    {
        // Track which compartment codes have been generated to avoid duplicates
        var generatedCodes = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        int count = 0;
        bool isFirst = true;

        // Try to get compartments from the loaded definitions (primary source)
        if (definitions.CompartmentsByUrl != null && definitions.CompartmentsByUrl.Count > 0)
        {
            foreach (var (url, compartment) in definitions.CompartmentsByUrl)
            {
                string? code = null;
                try
                {
                    code = compartment.Code?.ToString();
                }
                catch
                {
                    continue;
                }

                if (string.IsNullOrEmpty(code) || !generatedCodes.Add(code))
                    continue; // Skip duplicates

                if (!isFirst)
                    sb.AppendLine(",");

                GenerateCompartmentDefinitionFromObject(sb, compartment);
                isFirst = false;
                count++;
            }
        }

        // Additionally, try to load from static compartment.json if it exists (as fallback)
        string compartmentPath = GetCompartmentJsonPath(fhirVersion);
        if (File.Exists(compartmentPath))
        {
            try
            {
                string json = File.ReadAllText(compartmentPath);
                using JsonDocument doc = JsonDocument.Parse(json);

                if (doc.RootElement.TryGetProperty("entry", out JsonElement entries))
                {
                    foreach (JsonElement entry in entries.EnumerateArray())
                    {
                        if (!entry.TryGetProperty("resource", out JsonElement resource))
                            continue;

                        if (!resource.TryGetProperty("resourceType", out JsonElement resourceType) ||
                            resourceType.GetString() != "CompartmentDefinition")
                            continue;

                        string? code = resource.TryGetProperty("code", out var codeProp) ? codeProp.GetString() : null;
                        if (string.IsNullOrEmpty(code) || !generatedCodes.Add(code))
                            continue; // Skip duplicates

                        if (!isFirst)
                            sb.AppendLine(",");

                        GenerateCompartmentDefinitionFromJson(sb, resource);
                        isFirst = false;
                        count++;
                    }
                }
            }
            catch
            {
                // Silently continue if JSON parsing fails
            }
        }

        Console.WriteLine($"Generated {count} compartment definitions for {fhirVersion}");
    }

    private void GenerateCompartmentDefinitionFromObject(StringBuilder sb, Hl7.Fhir.Model.CompartmentDefinition compartment)
    {
        // Extract properties from Firely SDK CompartmentDefinition object
        string? code = null;
        try
        {
            code = compartment.Code?.ToString();
        }
        catch
        {
            // Handle unknown resource types gracefully by skipping
            return;
        }

        string? url = compartment.Url;

        if (string.IsNullOrEmpty(code) || string.IsNullOrEmpty(url))
            return;

        // Extract resources array
        var resources = new List<(string resourceType, List<string> parameters)>();
        if (compartment.Resource != null && compartment.Resource.Count > 0)
        {
            foreach (var res in compartment.Resource)
            {
                string? resCode = null;
                try
                {
                    resCode = res.Code?.ToString();
                }
                catch
                {
                    // Handle unknown resource types gracefully by skipping
                    continue;
                }

                if (string.IsNullOrEmpty(resCode))
                    continue;

                var parameters = new List<string>();
                if (res.Param != null)
                {
                    foreach (var param in res.Param)
                    {
                        if (!string.IsNullOrEmpty(param))
                            parameters.Add(param);
                    }
                }

                resources.Add((resCode, parameters));
            }
        }

        // Generate tuple entry
        sb.AppendLine($"            {{");
        sb.AppendLine($"                CompartmentType.{code},");
        sb.AppendLine($"                (");
        sb.AppendLine($"                    CompartmentType.{code},");
        sb.AppendLine($"                    new Uri(\"{EscapeString(url)}\"),");
        sb.AppendLine($"                    new List<(string Resource, IList<string> Params)>");
        sb.AppendLine($"                    {{");

        for (int i = 0; i < resources.Count; i++)
        {
            var (resourceType, parameters) = resources[i];
            sb.Append($"                        (\"{EscapeString(resourceType)}\", ");

            if (parameters.Count == 0)
            {
                sb.Append("new List<string>())");
            }
            else
            {
                sb.Append("new List<string> { ");
                sb.Append(string.Join(", ", parameters.Select(p => $"\"{EscapeString(p)}\"")));
                sb.Append(" })");
            }

            if (i < resources.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine($"                    }}");
        sb.AppendLine($"                )");
        sb.Append($"            }}");
    }

    private void GenerateCompartmentDefinitionFromJson(StringBuilder sb, JsonElement resource)
    {
        // Extract properties
        string? code = resource.TryGetProperty("code", out var codeProp) ? codeProp.GetString() : null;
        string? url = resource.TryGetProperty("url", out var urlProp) ? urlProp.GetString() : null;

        if (string.IsNullOrEmpty(code) || string.IsNullOrEmpty(url))
            return;

        // Extract resources array
        var resources = new List<(string resourceType, List<string> parameters)>();
        if (resource.TryGetProperty("resource", out var resourcesProp) && resourcesProp.ValueKind == JsonValueKind.Array)
        {
            foreach (var res in resourcesProp.EnumerateArray())
            {
                string? resCode = res.TryGetProperty("code", out var resCodeProp) ? resCodeProp.GetString() : null;
                if (string.IsNullOrEmpty(resCode))
                    continue;

                var parameters = new List<string>();
                if (res.TryGetProperty("param", out var paramsProp) && paramsProp.ValueKind == JsonValueKind.Array)
                {
                    foreach (var param in paramsProp.EnumerateArray())
                    {
                        string? paramStr = param.GetString();
                        if (!string.IsNullOrEmpty(paramStr))
                            parameters.Add(paramStr);
                    }
                }

                resources.Add((resCode, parameters));
            }
        }

        // Generate tuple entry
        sb.AppendLine($"            {{");
        sb.AppendLine($"                CompartmentType.{code},");
        sb.AppendLine($"                (");
        sb.AppendLine($"                    CompartmentType.{code},");
        sb.AppendLine($"                    new Uri(\"{EscapeString(url)}\"),");
        sb.AppendLine($"                    new List<(string Resource, IList<string> Params)>");
        sb.AppendLine($"                    {{");

        for (int i = 0; i < resources.Count; i++)
        {
            var (resourceType, parameters) = resources[i];
            sb.Append($"                        (\"{EscapeString(resourceType)}\", ");

            if (parameters.Count == 0)
            {
                sb.Append("new List<string>())");
            }
            else
            {
                sb.Append("new List<string> { ");
                sb.Append(string.Join(", ", parameters.Select(p => $"\"{EscapeString(p)}\"")));
                sb.Append(" })");
            }

            if (i < resources.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine($"                    }}");
        sb.AppendLine($"                )");
        sb.Append($"            }}");
    }

    private string GetCompartmentJsonPath(string fhirVersion)
    {
        // Resolve path to embedded compartment.json in Ignixa.Search project
        string baseDir = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "../../src", "Ignixa.Search", "Data"));

        string versionDir = fhirVersion switch
        {
            "R4" => "R4",
            "R4B" => "R4B",
            "R5" => "R5",
            "R6" => "R6",
            "STU3" => "Stu3",
            _ => throw new ArgumentException($"Unknown FHIR version: {fhirVersion}")
        };

        return Path.Combine(baseDir, versionDir, "compartment.json");
    }

    private string EscapeString(string value)
    {
        if (value == null)
            return "null";

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }
}

/// <summary>
/// Configuration for the C# Compartment generator.
/// </summary>
public sealed class CSharpCompartmentConfig
{
    /// <summary>Gets or sets the output directory for generated files.</summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>Gets or sets the namespace for generated classes.</summary>
    public string Namespace { get; set; } = "Sparky.Search.Generated";
}
