// <copyright file="CSharpCoreSchemaLanguage.cs" company="Ignixa Contributors">
//     Copyright (c) Ignixa Contributors. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

using System.Text;
using System.Text.RegularExpressions;
using Hl7.Fhir.Model;
using Microsoft.Health.Fhir.CodeGen.Language;
using Microsoft.Health.Fhir.CodeGen.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Models;
using Microsoft.Health.Fhir.CodeGenCommon.Packaging;
using Microsoft.Health.Fhir.CodeGen.FhirExtensions;

namespace Ignixa.Specification.Generators;

/// <summary>
/// Generates C# ISchema implementations using Ignixa.Abstractions interfaces.
/// This is the next-generation provider using IType and ITypeExtended with modern interfaces.
/// </summary>
public sealed class CSharpCoreSchemaLanguage : ILanguage
{
    private const string LanguageName = "CSharpCoreSchema";
    private StringConstantTracker? _constantTracker;

    /// <summary>Gets the language name.</summary>
    public string Name => LanguageName;

    /// <summary>Gets the configuration type.</summary>
    public Type ConfigType => typeof(CSharpCoreSchemaConfig);

    /// <summary>Gets the FHIR primitive type map (not used for this generator).</summary>
    public Dictionary<string, string> FhirPrimitiveTypeMap => new();

    /// <summary>Gets a value indicating whether this language is idempotent.</summary>
    public bool IsIdempotent => true;

    /// <summary>Exports the Core schema provider code.</summary>
    /// <param name="config">The configuration.</param>
    /// <param name="definitions">The definitions to export.</param>
    public void Export(object config, DefinitionCollection definitions)
    {
        if (config is not CSharpCoreSchemaConfig coreConfig)
        {
            throw new ArgumentException($"Configuration must be of type {nameof(CSharpCoreSchemaConfig)}", nameof(config));
        }

        // Get the FHIR version
        string fhirVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "R4",
            FhirReleases.FhirSequenceCodes.R4B => "R4B",
            FhirReleases.FhirSequenceCodes.R5 => "R5",
            FhirReleases.FhirSequenceCodes.R6 => "R6",
            FhirReleases.FhirSequenceCodes.STU3 => "STU3",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Get Core FhirVersion enum value
        string coreFhirVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "R4",
            FhirReleases.FhirSequenceCodes.R4B => "R4B",
            FhirReleases.FhirSequenceCodes.R5 => "R5",
            FhirReleases.FhirSequenceCodes.R6 => "R6",
            FhirReleases.FhirSequenceCodes.STU3 => "STU3",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Get full FHIR version string
        string fullVersion = definitions.FhirSequence switch
        {
            FhirReleases.FhirSequenceCodes.R4 => "4.0.1",
            FhirReleases.FhirSequenceCodes.R4B => "4.3.0",
            FhirReleases.FhirSequenceCodes.R5 => "5.0.0",
            FhirReleases.FhirSequenceCodes.R6 => "6.0.0-ballot2",
            FhirReleases.FhirSequenceCodes.STU3 => "3.0.2",
            _ => throw new ArgumentException($"Unsupported FHIR version: {definitions.FhirSequence}")
        };

        // Create output directory
        string outputDir = Path.GetFullPath(coreConfig.OutputDirectory);
        Directory.CreateDirectory(outputDir);

        // Generate the Core schema provider class
        string outputPath = Path.Combine(outputDir, $"{fhirVersion}CoreSchemaProvider.g.cs");
        string code = GenerateCoreProviderCode(fhirVersion, coreFhirVersion, fullVersion, definitions, coreConfig);

        File.WriteAllText(outputPath, code, Encoding.UTF8);

        Console.WriteLine($"Generated {outputPath}");
    }

    private string GenerateCoreProviderCode(string fhirVersion, string coreFhirVersion, string fullVersion, DefinitionCollection definitions, CSharpCoreSchemaConfig config)
    {
        // Initialize the constant tracker and perform first pass to collect strings
        _constantTracker = new StringConstantTracker();
        CollectStringsForTracking(definitions);
        _constantTracker.Complete();

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// <copyright file=\"" + $"{fhirVersion}CoreSchemaProvider.g.cs" + "\" company=\"Ignixa Contributors\">");
        sb.AppendLine("//     Copyright (c) Ignixa Contributors. All rights reserved.");
        sb.AppendLine("//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.");
        sb.AppendLine("// </copyright>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Ignixa.Abstractions;");
        sb.AppendLine("using Ignixa.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Pre-generated IFhirSchemaProvider for FHIR {fhirVersion}.");
        sb.AppendLine("/// This provider uses IType and ITypeExtended interfaces for type metadata.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {fhirVersion}CoreSchemaProvider : Ignixa.Specification.IFhirSchemaProvider");
        sb.AppendLine("{");

        // ISchema.Version property (explicit interface implementation)
        sb.AppendLine($"    Ignixa.Abstractions.FhirVersion Ignixa.Abstractions.ISchema.Version => Ignixa.Abstractions.FhirVersion.{coreFhirVersion};");
        sb.AppendLine();

        // IFhirSchemaProvider.Version property (using FhirSpecification)
        // Note: FhirSpecification enum uses "Stu3" not "STU3"
        string fhirSpecValue = coreFhirVersion == "STU3" ? "Stu3" : coreFhirVersion;
        sb.AppendLine($"    public FhirSpecification Version => FhirSpecification.{fhirSpecValue};");
        sb.AppendLine();

        // FullVersion property
        sb.AppendLine($"    public string FullVersion => \"{fullVersion}\";");
        sb.AppendLine();

        // ResourceTypeNames property - collect resource type names
        var resourceTypeNames = definitions.ResourcesByName.Keys.OrderBy(x => x).ToList();
        sb.AppendLine($"    public IReadOnlySet<string> ResourceTypeNames => _resourceTypeNames;");
        sb.AppendLine();
        sb.AppendLine($"    private static readonly HashSet<string> _resourceTypeNames = new(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");
        foreach (var name in resourceTypeNames)
        {
            sb.AppendLine($"        \"{name}\",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // GetTypeDefinition method
        sb.AppendLine("    public Ignixa.Abstractions.IType? GetTypeDefinition(string typeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _types.TryGetValue(typeName, out var type) ? type : null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // IsKnownType method
        sb.AppendLine("    public bool IsKnownType(string typeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _types.ContainsKey(typeName);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate Constants class
        _constantTracker.GenerateConstantsClass(sb);

        // Generate types dictionary
        GenerateCoreTypesDictionary(sb, fhirVersion, definitions);

        // Generate nested CoreType class
        GenerateCoreTypeClass(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void CollectStringsForTracking(DefinitionCollection definitions)
    {
        // Collect all types (primitives, complex types, resources, and BackboneElements)
        var allTypes = new List<(string Name, StructureDefinition SD, bool IsResource, string? BackbonePath)>();

        foreach (var kvp in definitions.PrimitiveTypesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, false, null));
        }

        foreach (var kvp in definitions.ComplexTypesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, false, null));
        }

        foreach (var kvp in definitions.ResourcesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, true, null));

            // Extract BackboneElement types
            var backboneElements = ExtractBackboneElements(kvp.Value);
            foreach (var (backboneName, backbonePath) in backboneElements)
            {
                allTypes.Add((backboneName, kvp.Value, false, backbonePath));
            }
        }

        // Scan all elements to track string usage
        foreach (var (name, sd, _, backbonePath) in allTypes)
        {
            var elements = backbonePath != null
                ? sd.cgElements(forBackbonePath: backbonePath, topLevelOnly: true, includeRoot: false, skipSlices: true).ToList()
                : sd.cgElements(topLevelOnly: true, includeRoot: false, skipSlices: true).ToList();

            foreach (var element in elements)
            {
                TrackElementStrings(element);
            }
        }
    }

    private void TrackElementStrings(ElementDefinition element)
    {
        if (_constantTracker == null)
            return;

        // Track constraint keys, expressions, and human text
        if (element.Constraint != null)
        {
            foreach (var constraint in element.Constraint)
            {
                if (!string.IsNullOrEmpty(constraint.Key))
                    _constantTracker.Track(constraint.Key);
                if (!string.IsNullOrEmpty(constraint.Expression))
                    _constantTracker.Track(constraint.Expression);
                if (!string.IsNullOrEmpty(constraint.Human))
                    _constantTracker.Track(constraint.Human);
            }
        }

        // Track binding ValueSet URLs
        if (element.Binding != null && !string.IsNullOrEmpty(element.Binding.ValueSet))
        {
            _constantTracker.Track(element.Binding.ValueSet);
        }

        // Track type names
        foreach (var type in element.Type)
        {
            if (!string.IsNullOrEmpty(type.Code))
            {
                string normalized = NormalizeFhirPathTypeUrl(type.Code);
                _constantTracker.Track(normalized);
            }
        }
    }

    private void GenerateCoreTypesDictionary(StringBuilder sb, string fhirVersion, DefinitionCollection definitions)
    {
        sb.AppendLine("    private static readonly Dictionary<string, Ignixa.Abstractions.IType> _types = new(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");

        // Collect all types (primitives, complex types, resources, and BackboneElements)
        var allTypes = new List<(string Name, StructureDefinition SD, bool IsResource, string? BackbonePath)>();

        foreach (var kvp in definitions.PrimitiveTypesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, false, null));
        }

        foreach (var kvp in definitions.ComplexTypesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, false, null));
        }

        foreach (var kvp in definitions.ResourcesByName)
        {
            allTypes.Add((kvp.Key, kvp.Value, true, null));

            // Extract BackboneElement types
            var backboneElements = ExtractBackboneElements(kvp.Value);
            foreach (var (backboneName, backbonePath) in backboneElements)
            {
                allTypes.Add((backboneName, kvp.Value, false, backbonePath));
            }
        }

        // Sort alphabetically
        allTypes = allTypes.OrderBy(t => t.Name).ToList();

        foreach (var (name, sd, isResource, backbonePath) in allTypes)
        {
            bool isAbstract = sd.Abstract ?? false;
            string primitive = MapToPrimitive(name);

            sb.AppendLine($"        [\"{name}\"] = new CoreType(");
            sb.AppendLine($"            name: \"{name}\",");
            sb.AppendLine($"            primitive: Ignixa.Abstractions.FhirPrimitive.{primitive},");
            sb.AppendLine($"            isResource: {(isResource ? "true" : "false")},");
            sb.AppendLine($"            isAbstract: {(isAbstract ? "true" : "false")},");
            sb.AppendLine($"            isChoiceElement: false,"); // Top-level types are not choice elements
            sb.AppendLine($"            isModifier: false,"); // Will be set per-element in children
            sb.AppendLine($"            isCollection: false,");
            sb.AppendLine($"            isRequired: false,");
            sb.AppendLine($"            inSummary: false,");
            sb.AppendLine($"            order: 0,");
            sb.AppendLine($"            childrenFactory: () => {GetSafeMethodName(name)}_Children(),");
            sb.AppendLine($"            min: 0,");
            sb.AppendLine($"            max: \"1\",");
            sb.AppendLine($"            constraints: null,");
            sb.AppendLine($"            binding: null,");
            sb.AppendLine($"            fixedValue: null,");
            sb.AppendLine($"            patternValue: null,");
            sb.AppendLine($"            types: new[] {{ new Ignixa.Abstractions.TypeReferenceDefinition(\"{name}\") }},");
            sb.AppendLine($"            defaultTypeName: \"{name}\",");
            sb.AppendLine($"            referenceTargets: null,");
            sb.AppendLine($"            contentReference: null");
            sb.AppendLine($"        ),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        // Generate child factory methods for each type
        foreach (var (name, sd, _, backbonePath) in allTypes)
        {
            GenerateChildrenMethod(sb, name, sd, definitions, backbonePath);
        }
    }

    private void GenerateChildrenMethod(StringBuilder sb, string typeName, StructureDefinition sd, DefinitionCollection definitions, string? backbonePath = null)
    {
        string safeName = GetSafeMethodName(typeName);

        sb.AppendLine($"    private static IReadOnlyList<Ignixa.Abstractions.IType> {safeName}_Children()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new Ignixa.Abstractions.IType[]");
        sb.AppendLine("        {");

        // Get elements for this type
        var elements = backbonePath != null
            ? sd.cgElements(forBackbonePath: backbonePath, topLevelOnly: true, includeRoot: false, skipSlices: true).ToList()
            : sd.cgElements(topLevelOnly: true, includeRoot: false, skipSlices: true).ToList();

        int order = 0;
        foreach (var element in elements)
        {
            GenerateCoreTypeChild(sb, element, definitions, order);
            order++;
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void GenerateCoreTypeChild(StringBuilder sb, ElementDefinition element, DefinitionCollection definitions, int order)
    {
        string elementName = element.cgName();
        bool isCollection = element.cgIsArray();
        bool isRequired = element.cgCardinalityMin() > 0;
        bool inSummary = element.IsSummary ?? false;
        bool isChoiceElement = element.Path.EndsWith("[x]", StringComparison.Ordinal);
        bool isModifier = element.IsModifier ?? false;

        // Strip [x] suffix from choice element names
        if (isChoiceElement && elementName.EndsWith("[x]", StringComparison.Ordinal))
        {
            elementName = elementName.Substring(0, elementName.Length - 3);
        }

        // Determine if this element is a resource type
        bool isResource = element.Type.Any(t => definitions.ResourcesByName.ContainsKey(t.Code ?? string.Empty));

        // Get type names
        var typeNames = element.Type.Select(t => NormalizeFhirPathTypeUrl(t.Code ?? "Element")).ToList();
        string typeName = typeNames.FirstOrDefault() ?? "Element";
        string primitive = MapToPrimitive(typeName);

        // Extract extended metadata
        var (min, max, constraints, binding, fixedValue, patternValue, typeArray, defaultTypeName, referenceTargets, contentReference, slicing) =
            ExtractExtendedMetadata(element, definitions, typeName);

        sb.AppendLine($"            new CoreType(");
        sb.AppendLine($"                name: \"{EscapeString(elementName)}\",");
        sb.AppendLine($"                primitive: Ignixa.Abstractions.FhirPrimitive.{primitive},");
        sb.AppendLine($"                isResource: {(isResource ? "true" : "false")},");
        sb.AppendLine($"                isAbstract: false,");
        sb.AppendLine($"                isChoiceElement: {(isChoiceElement ? "true" : "false")},");
        sb.AppendLine($"                isModifier: {(isModifier ? "true" : "false")},");
        sb.AppendLine($"                isCollection: {(isCollection ? "true" : "false")},");
        sb.AppendLine($"                isRequired: {(isRequired ? "true" : "false")},");
        sb.AppendLine($"                inSummary: {(inSummary ? "true" : "false")},");
        sb.AppendLine($"                order: {order},");
        sb.AppendLine($"                childrenFactory: null,"); // Children are resolved via type lookup
        sb.AppendLine($"                min: {min},");
        sb.AppendLine($"                max: {max},");
        sb.AppendLine($"                constraints: {constraints},");
        sb.AppendLine($"                binding: {binding},");
        sb.AppendLine($"                fixedValue: {fixedValue},");
        sb.AppendLine($"                patternValue: {patternValue},");
        sb.AppendLine($"                types: {typeArray},");
        sb.AppendLine($"                defaultTypeName: {defaultTypeName},");
        sb.AppendLine($"                referenceTargets: {referenceTargets},");
        sb.AppendLine($"                contentReference: {contentReference},");
        sb.AppendLine($"                slicing: {slicing}");
        sb.AppendLine($"            ),");
    }

    private (string min, string max, string constraints, string binding, string fixedValue, string patternValue, string typeArray, string defaultTypeName, string referenceTargets, string contentReference, string slicing)
        ExtractExtendedMetadata(ElementDefinition element, DefinitionCollection definitions, string elementTypeName)
    {
        // 1. Min/Max cardinality
        string min = element.Min.HasValue ? element.Min.Value.ToString() : "null";
        string max = !string.IsNullOrEmpty(element.Max) ? $"\"{EscapeString(element.Max)}\"" : "null";

        // 2. Constraints
        string constraints = "null";
        if (element.Constraint != null && element.Constraint.Any())
        {
            // Track the AppliesTo element type name for constant generation
            _constantTracker?.Track(elementTypeName);

            var constraintList = element.Constraint
                .Select(c =>
                {
                    // Use constant reference for constraint key if available
                    string keyValue = c.Key ?? "";
                    string key = _constantTracker?.GetConstantReference(keyValue) ?? $"\"{EscapeString(keyValue)}\"";

                    string severityValue = c.Severity?.ToString()?.ToLowerInvariant() ?? "error";
                    string severity = $"\"{EscapeString(severityValue)}\"";

                    // Use constants for human and expression if available
                    string humanValue = c.Human ?? "";
                    string human = _constantTracker?.GetConstantReference(humanValue) ?? $"\"{EscapeString(humanValue)}\"";

                    string expressionValue = c.Expression ?? "";
                    string expression = _constantTracker?.GetConstantReference(expressionValue) ?? $"\"{EscapeString(expressionValue)}\"";

                    string xpath = c.Xpath != null ? $"\"{EscapeString(c.Xpath)}\"" : "null";

                    return $"new Ignixa.Abstractions.ConstraintDefinition {{ Key = {key}, Severity = {severity}, Human = {human}, Expression = {expression}, Xpath = {xpath} }}";
                })
                .ToList();

            if (constraintList.Count > 0)
            {
                constraints = $"new[] {{ {string.Join(", ", constraintList)} }}";
            }
        }

        // 3. Binding
        string binding = "null";
        if (element.Binding != null && !string.IsNullOrEmpty(element.Binding.ValueSet))
        {
            string strength = element.Binding.Strength?.ToString() ?? "Unknown";
            string valueSetUrl = _constantTracker?.GetConstantReference(element.Binding.ValueSet) ?? $"\"{EscapeString(element.Binding.ValueSet)}\"";
            binding = $"new Ignixa.Abstractions.BindingMetadata({valueSetUrl}, \"{strength}\")";
        }

        // 4. Fixed Value (serialize as JSON)
        string fixedValue = "null";
        if (element.Fixed != null)
        {
            string json = SerializeToJson(element.Fixed);
            if (!string.IsNullOrEmpty(json))
            {
                fixedValue = $"\"{EscapeString(json)}\"";
            }
        }

        // 5. Pattern Value (serialize as JSON)
        string patternValue = "null";
        if (element.Pattern != null)
        {
            string json = SerializeToJson(element.Pattern);
            if (!string.IsNullOrEmpty(json))
            {
                patternValue = $"\"{EscapeString(json)}\"";
            }
        }

        // 6. Type array (normalize FHIRPath URLs and create TypeReference objects)
        string typeArray = "null";
        if (element.Type != null && element.Type.Any())
        {
            var typeRefs = element.Type.Select(t =>
            {
                string code = NormalizeFhirPathTypeUrl(t.Code ?? "Element");
                string codeRef = _constantTracker?.GetConstantReference(code) ?? $"\"{EscapeString(code)}\"";

                string profile = "null";
                if (!string.IsNullOrEmpty(t.Profile?.FirstOrDefault()))
                {
                    profile = $"\"{EscapeString(t.Profile.First())}\"";
                }

                string targetProfile = "null";
                if (!string.IsNullOrEmpty(t.TargetProfile?.FirstOrDefault()))
                {
                    targetProfile = $"\"{EscapeString(t.TargetProfile.First())}\"";
                }

                string aggregation = "null";
                if (t.Aggregation != null && t.Aggregation.Any())
                {
                    var aggValues = t.Aggregation.Select(a => $"\"{EscapeString(a.ToString() ?? "")}\"");
                    aggregation = $"new[] {{ {string.Join(", ", aggValues)} }}";
                }

                string versioning = "null";
                if (t.Versioning.HasValue)
                {
                    versioning = $"\"{EscapeString(t.Versioning.Value.ToString() ?? "")}\"";
                }

                return $"new Ignixa.Abstractions.TypeReferenceDefinition({codeRef}, {profile}, {targetProfile}, {aggregation}, {versioning})";
            });
            typeArray = $"new[] {{ {string.Join(", ", typeRefs)} }}";
        }

        // 7. Default type name
        string defaultTypeName = "null";
        var firstTypeCode = element.Type?.FirstOrDefault()?.Code;
        if (firstTypeCode != null)
        {
            string firstType = NormalizeFhirPathTypeUrl(firstTypeCode);
            defaultTypeName = _constantTracker?.GetConstantReference(firstType) ?? $"\"{EscapeString(firstType)}\"";
        }

        // 8. Reference Targets
        string referenceTargets = "null";
        var referenceType = element.Type?.FirstOrDefault(t => t.Code == "Reference");
        if (referenceType?.TargetProfile != null && referenceType.TargetProfile.Any())
        {
            var targets = referenceType.TargetProfile
                .Select(url => url.Split('/').Last())
                .Where(t => !string.IsNullOrEmpty(t))
                .ToList();

            if (targets.Count > 0)
            {
                referenceTargets = $"new[] {{ {string.Join(", ", targets.Select(t => $"\"{EscapeString(t)}\""))} }}";
            }
        }

        // 9. Content Reference
        string contentReference = "null";
        if (!string.IsNullOrEmpty(element.ContentReference))
        {
            contentReference = $"\"{EscapeString(element.ContentReference)}\"";
        }

        // 10. Slicing
        string slicing = "null";
        if (element.Slicing != null)
        {
            var discriminators = element.Slicing.Discriminator?
                .Select(d => $"{d.Type}:{d.Path}")
                .ToArray() ?? Array.Empty<string>();

            string rules = element.Slicing.Rules?.ToString() ?? "Open";
            bool ordered = element.Slicing.Ordered ?? false;

            if (discriminators.Length > 0)
            {
                string discriminatorArray = $"new[] {{ {string.Join(", ", discriminators.Select(d => $"\"{EscapeString(d)}\""))} }}";
                slicing = $"new Ignixa.Abstractions.SlicingMetadata({discriminatorArray}, \"{rules}\", {(ordered ? "true" : "false")})";
            }
        }

        return (min, max, constraints, binding, fixedValue, patternValue, typeArray, defaultTypeName, referenceTargets, contentReference, slicing);
    }

    private string SerializeToJson(DataType value)
    {
        try
        {
            // Use Firely SDK's JSON serializer
            var serializer = new Hl7.Fhir.Serialization.FhirJsonSerializer();
            return serializer.SerializeToString(value);
        }
        catch
        {
            // Fallback to simple string representation
            return value.ToString() ?? string.Empty;
        }
    }

    private void GenerateCoreTypeClass(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Core implementation of ITypeExtended for FHIR type metadata with extended properties.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private sealed class CoreType : Ignixa.Abstractions.ITypeExtended");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly Func<IReadOnlyList<Ignixa.Abstractions.IType>>? _childrenFactory;");
        sb.AppendLine("        private IReadOnlyList<Ignixa.Abstractions.IType>? _children;");
        sb.AppendLine();
        sb.AppendLine("        public CoreType(");
        sb.AppendLine("            string name,");
        sb.AppendLine("            Ignixa.Abstractions.FhirPrimitive primitive,");
        sb.AppendLine("            bool isResource,");
        sb.AppendLine("            bool isAbstract,");
        sb.AppendLine("            bool isChoiceElement,");
        sb.AppendLine("            bool isModifier,");
        sb.AppendLine("            bool isCollection,");
        sb.AppendLine("            bool isRequired,");
        sb.AppendLine("            bool inSummary,");
        sb.AppendLine("            int order,");
        sb.AppendLine("            Func<IReadOnlyList<Ignixa.Abstractions.IType>>? childrenFactory,");
        sb.AppendLine("            int? min = null,");
        sb.AppendLine("            string? max = null,");
        sb.AppendLine("            IReadOnlyList<Ignixa.Abstractions.IConstraint>? constraints = null,");
        sb.AppendLine("            Ignixa.Abstractions.IBinding? binding = null,");
        sb.AppendLine("            object? fixedValue = null,");
        sb.AppendLine("            object? patternValue = null,");
        sb.AppendLine("            IReadOnlyList<Ignixa.Abstractions.ITypeReference>? types = null,");
        sb.AppendLine("            string? defaultTypeName = null,");
        sb.AppendLine("            IReadOnlyList<string>? referenceTargets = null,");
        sb.AppendLine("            string? contentReference = null,");
        sb.AppendLine("            Ignixa.Abstractions.SlicingMetadata? slicing = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            Info = new Ignixa.Abstractions.TypeInfo(name, primitive, isResource, isAbstract, isChoiceElement, isModifier);");
        sb.AppendLine("            IsCollection = isCollection;");
        sb.AppendLine("            IsRequired = isRequired;");
        sb.AppendLine("            InSummary = inSummary;");
        sb.AppendLine("            Order = order;");
        sb.AppendLine("            _childrenFactory = childrenFactory;");
        sb.AppendLine("            Min = min ?? 0;");
        sb.AppendLine("            Max = max ?? \"*\";");
        sb.AppendLine("            Constraints = constraints ?? Array.Empty<Ignixa.Abstractions.IConstraint>();");
        sb.AppendLine("            Binding = binding;");
        sb.AppendLine("            FixedValue = fixedValue;");
        sb.AppendLine("            PatternValue = patternValue;");
        sb.AppendLine("            Types = types ?? (defaultTypeName != null ? new[] { new Ignixa.Abstractions.TypeReferenceDefinition(defaultTypeName) } : new[] { new Ignixa.Abstractions.TypeReferenceDefinition(name) });");
        sb.AppendLine("            DefaultTypeName = defaultTypeName;");
        sb.AppendLine("            ReferenceTargets = referenceTargets ?? Array.Empty<string>();");
        sb.AppendLine("            ContentReference = contentReference;");
        sb.AppendLine("            Slicing = slicing;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // IType properties");
        sb.AppendLine("        public Ignixa.Abstractions.TypeInfo Info { get; }");
        sb.AppendLine("        public bool IsCollection { get; }");
        sb.AppendLine("        public bool IsRequired { get; }");
        sb.AppendLine("        public bool InSummary { get; }");
        sb.AppendLine("        public int Order { get; }");
        sb.AppendLine();
        sb.AppendLine("        public IReadOnlyList<Ignixa.Abstractions.IType> Children");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_children == null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _children = _childrenFactory?.Invoke() ?? Array.Empty<Ignixa.Abstractions.IType>();");
        sb.AppendLine("                }");
        sb.AppendLine("                return _children;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // ITypeExtended properties");
        sb.AppendLine("        public int Min { get; }");
        sb.AppendLine("        public string Max { get; }");
        sb.AppendLine("        public IReadOnlyList<Ignixa.Abstractions.IConstraint> Constraints { get; }");
        sb.AppendLine("        public Ignixa.Abstractions.IBinding? Binding { get; }");
        sb.AppendLine("        public object? FixedValue { get; }");
        sb.AppendLine("        public object? PatternValue { get; }");
        sb.AppendLine("        public IReadOnlyList<Ignixa.Abstractions.ITypeReference> Types { get; }");
        sb.AppendLine("        public string? DefaultTypeName { get; }");
        sb.AppendLine("        public IReadOnlyList<string> ReferenceTargets { get; }");
        sb.AppendLine("        public string? ContentReference { get; }");
        sb.AppendLine("        public Ignixa.Abstractions.SlicingMetadata? Slicing { get; }");
        sb.AppendLine("    }");
    }

    private string MapToPrimitive(string typeName)
    {
        // Map FHIR type names to FhirPrimitive enum values
        return typeName switch
        {
            "boolean" => "Boolean",
            "integer" => "Integer",
            "string" => "String",
            "decimal" => "Decimal",
            "uri" => "Uri",
            "url" => "Url",
            "canonical" => "Canonical",
            "base64Binary" => "Base64Binary",
            "instant" => "Instant",
            "date" => "Date",
            "dateTime" => "DateTime",
            "time" => "Time",
            "code" => "Code",
            "oid" => "Oid",
            "id" => "Id",
            "markdown" => "Markdown",
            "unsignedInt" => "UnsignedInt",
            "positiveInt" => "PositiveInt",
            "uuid" => "Uuid",
            "integer64" => "Integer64",
            _ => "None" // Complex types
        };
    }

    private string NormalizeFhirPathTypeUrl(string typeCode)
    {
        return typeCode switch
        {
            "http://hl7.org/fhirpath/System.String" => "string",
            "http://hl7.org/fhirpath/System.Boolean" => "boolean",
            "http://hl7.org/fhirpath/System.Integer" => "integer",
            "http://hl7.org/fhirpath/System.Decimal" => "decimal",
            "http://hl7.org/fhirpath/System.DateTime" => "dateTime",
            "http://hl7.org/fhirpath/System.Date" => "date",
            "http://hl7.org/fhirpath/System.Time" => "time",
            "http://hl7.org/fhirpath/System.Quantity" => "Quantity",
            _ => typeCode
        };
    }

    private List<(string TypeName, string ElementPath)> ExtractBackboneElements(StructureDefinition sd)
    {
        var backboneElements = new List<(string TypeName, string ElementPath)>();

        var allElements = sd.cgElements(topLevelOnly: false, includeRoot: false, skipSlices: true);

        foreach (var element in allElements)
        {
            if (element.Type.Any(t => t.Code == "BackboneElement"))
            {
                string elementPath = element.Path;
                int lastDotIndex = elementPath.LastIndexOf('.');
                if (lastDotIndex > 0)
                {
                    string baseName = elementPath.Substring(0, lastDotIndex);
                    string elementName = elementPath.Substring(lastDotIndex + 1);
                    string capitalizedElementName = CapitalizeFirstLetter(elementName);
                    string typeName = $"{baseName}.{capitalizedElementName}";

                    backboneElements.Add((typeName, elementPath));
                }
            }
        }

        return backboneElements;
    }

    private string GetSafeMethodName(string typeName)
    {
        return typeName.Replace("-", "_").Replace(".", "_").Replace("#", "Sharp");
    }

    private string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private string CapitalizeFirstLetter(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        if (char.IsUpper(value[0]))
            return value;

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }
}

/// <summary>
/// Configuration for the C# Core Schema generator.
/// </summary>
public sealed class CSharpCoreSchemaConfig
{
    /// <summary>Gets or sets the output directory for generated files.</summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>Gets or sets the namespace for generated classes.</summary>
    public string Namespace { get; set; } = "Ignixa.Specification.Generated";
}

/// <summary>
/// Tracks string usage and generates constants for frequently-used strings.
/// </summary>
internal sealed class StringConstantTracker
{
    private const int MinUsageThreshold = 3;
    private readonly Dictionary<string, int> _usageCounts = new();
    private readonly Dictionary<string, string> _stringToConstantName = new();
    private readonly HashSet<string> _usedConstantNames = new();

    /// <summary>Tracks a string usage.</summary>
    public void Track(string value)
    {
        if (string.IsNullOrEmpty(value))
            return;

        _usageCounts[value] = _usageCounts.GetValueOrDefault(value) + 1;
    }

    /// <summary>Finalizes tracking and assigns constant names to frequently-used strings.</summary>
    public void Complete()
    {
        foreach (var kvp in _usageCounts.Where(x => x.Value >= MinUsageThreshold).OrderByDescending(x => x.Value))
        {
            string constantName = GenerateConstantName(kvp.Key);
            _stringToConstantName[kvp.Key] = constantName;
        }
    }

    /// <summary>Gets the constant reference for a string, or null if not tracked.</summary>
    public string? GetConstantReference(string value)
    {
        return _stringToConstantName.TryGetValue(value, out var constantName) ? $"Constants.{constantName}" : null;
    }

    /// <summary>Generates the Constants class code.</summary>
    public void GenerateConstantsClass(StringBuilder sb)
    {
        if (_stringToConstantName.Count == 0)
            return;

        sb.AppendLine("    private static class Constants");
        sb.AppendLine("    {");

        // Group by category
        var constraintKeys = _stringToConstantName.Where(kvp => kvp.Value.StartsWith("Key_")).OrderBy(kvp => kvp.Value);
        var expressions = _stringToConstantName.Where(kvp => kvp.Value.StartsWith("Expr_")).OrderBy(kvp => kvp.Value);
        var humanTexts = _stringToConstantName.Where(kvp => kvp.Value.StartsWith("Human_")).OrderBy(kvp => kvp.Value);
        var valueSets = _stringToConstantName.Where(kvp => kvp.Value.StartsWith("VS_")).OrderBy(kvp => kvp.Value);
        var others = _stringToConstantName.Where(kvp => !kvp.Value.StartsWith("Key_") && !kvp.Value.StartsWith("Expr_") && !kvp.Value.StartsWith("Human_") && !kvp.Value.StartsWith("VS_")).OrderBy(kvp => kvp.Value);

        if (constraintKeys.Any())
        {
            sb.AppendLine("        // Constraint keys");
            foreach (var kvp in constraintKeys)
            {
                string escaped = EscapeStringStatic(kvp.Key);
                sb.AppendLine($"        public const string {kvp.Value} = \"{escaped}\";");
            }
            sb.AppendLine();
        }

        if (expressions.Any())
        {
            sb.AppendLine("        // Constraint expressions");
            foreach (var kvp in expressions)
            {
                string escaped = EscapeStringStatic(kvp.Key);
                sb.AppendLine($"        public const string {kvp.Value} = \"{escaped}\";");
            }
            sb.AppendLine();
        }

        if (humanTexts.Any())
        {
            sb.AppendLine("        // Human-readable constraint descriptions");
            foreach (var kvp in humanTexts)
            {
                string escaped = EscapeStringStatic(kvp.Key);
                sb.AppendLine($"        public const string {kvp.Value} = \"{escaped}\";");
            }
            sb.AppendLine();
        }

        if (valueSets.Any())
        {
            sb.AppendLine("        // ValueSet URLs");
            foreach (var kvp in valueSets)
            {
                string escaped = EscapeStringStatic(kvp.Key);
                sb.AppendLine($"        public const string {kvp.Value} = \"{escaped}\";");
            }
            sb.AppendLine();
        }

        if (others.Any())
        {
            sb.AppendLine("        // Other common strings");
            foreach (var kvp in others)
            {
                string escaped = EscapeStringStatic(kvp.Key);
                sb.AppendLine($"        public const string {kvp.Value} = \"{escaped}\";");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string GenerateConstantName(string value)
    {
        string prefix = DeterminePrefix(value);
        string baseName = SanitizeForIdentifier(value);

        // Truncate to first 40 chars
        if (baseName.Length > 40)
            baseName = baseName.Substring(0, 40);

        string candidateName = prefix + baseName;

        // Handle collisions
        if (_usedConstantNames.Contains(candidateName))
        {
            int counter = 2;
            while (_usedConstantNames.Contains($"{candidateName}{counter}"))
                counter++;
            candidateName = $"{candidateName}{counter}";
        }

        _usedConstantNames.Add(candidateName);
        return candidateName;
    }

    private static string DeterminePrefix(string value)
    {
        // Check if it's a constraint key (short, lowercase with hyphens like "ele-1", "dom-2")
        if (value.Length < 10 && value.Contains("-") && value.Length > 0 && char.IsLower(value[0]))
        {
            return "Key_";
        }

        // Check if it's a ValueSet URL
        if (value.StartsWith("http://hl7.org/fhir/ValueSet/", StringComparison.Ordinal) ||
            value.StartsWith("http://terminology.hl7.org/ValueSet/", StringComparison.Ordinal))
        {
            return "VS_";
        }

        // Check if it looks like a FHIRPath expression (contains operators or function calls)
        if (value.Contains("(") || value.Contains(".") || value.Contains("=") || value.Contains("or ") || value.Contains("and "))
        {
            return "Expr_";
        }

        // Check if it's human-readable text (starts with capital letter and contains spaces)
        if (value.Length > 0 && char.IsUpper(value[0]) && value.Contains(" "))
        {
            return "Human_";
        }

        return "Str_";
    }

    private static string SanitizeForIdentifier(string value)
    {
        // For ValueSet URLs, extract the last segment
        if (value.StartsWith("http://", StringComparison.Ordinal) || value.StartsWith("https://", StringComparison.Ordinal))
        {
            var parts = value.Split('/');
            value = parts[^1];
            // Handle query strings
            if (value.Contains('?'))
                value = value.Substring(0, value.IndexOf('?'));
        }

        // Convert to PascalCase-like identifier
        var sb = new StringBuilder();
        bool capitalizeNext = true;

        foreach (char c in value)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
            else if (c == ' ' || c == '-' || c == '_' || c == '.' || c == ':' || c == '/')
            {
                capitalizeNext = true;
            }
        }

        string result = sb.ToString();

        // Ensure it doesn't start with a digit
        if (result.Length > 0 && char.IsDigit(result[0]))
            result = "N" + result;

        // Ensure it's not empty
        if (string.IsNullOrEmpty(result))
            result = "Empty";

        return result;
    }

    private static string EscapeStringStatic(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
