// <auto-generated />
using System;
using Ignixa.DataLayer.SqlEntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ignixa.DataLayer.SqlEntityFramework.Migrations
{
    [DbContext(typeof(FhirDbContext))]
    [Migration("20251108000000_AddPackageResourceAndTerminologyIndexes")]
    partial class AddPackageResourceAndTerminologyIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.BackgroundJobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("HeartbeatDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("OrchestrationInstanceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Progress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Worker")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("JobId")
                        .HasName("PK_BackgroundJobs");

                    b.HasIndex("CreateDate")
                        .HasDatabaseName("IX_BackgroundJobs_CreateDate");

                    b.HasIndex("HeartbeatDate")
                        .HasDatabaseName("IX_BackgroundJobs_HeartbeatDate");

                    b.HasIndex("JobType")
                        .HasDatabaseName("IX_BackgroundJobs_JobType");

                    b.HasIndex("OrchestrationInstanceId")
                        .HasDatabaseName("IX_BackgroundJobs_OrchestrationInstanceId")
                        .HasFilter("[OrchestrationInstanceId] IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BackgroundJobs_Status");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.DateTimeSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDateTime");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDateTime");

                    b.Property<bool>("IsLongerThanADay")
                        .HasColumnType("bit")
                        .HasColumnName("IsLongerThanADay");

                    b.Property<bool>("IsMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMax");

                    b.Property<bool>("IsMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMin");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "StartDateTime");

                    b.ToTable("DateTimeSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.NumberSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<decimal>("HighValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("HighValue");

                    b.Property<decimal>("LowValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("LowValue");

                    b.Property<decimal?>("SingleValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("SingleValue");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId");

                    b.ToTable("NumberSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.PackageResourceEntity", b =>
                {
                    b.Property<long>("PackageResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PackageResourceId"));

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResourceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FhirVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("LoadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PackageResourceId")
                        .HasName("PK_PackageResource");

                    b.HasIndex("LoadedDate")
                        .HasDatabaseName("IX_PackageResource_LoadedDate");

                    b.HasIndex("PackageId", "PackageVersion")
                        .HasDatabaseName("IX_PackageResource_Package");

                    b.HasIndex("Canonical", "Version")
                        .HasDatabaseName("IX_PackageResource_Canonical_Version")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ResourceType", "Canonical")
                        .HasDatabaseName("IX_PackageResource_ResourceType_Canonical")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PackageId", "PackageVersion", "Canonical")
                        .IsUnique()
                        .HasDatabaseName("UQ_PackageResource_Canonical");

                    b.ToTable("PackageResource", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.QuantityCodeEntity", b =>
                {
                    b.Property<int>("QuantityCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuantityCodeId"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("QuantityCodeId")
                        .HasName("PK_QuantityCode");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuantityCode_Value");

                    b.ToTable("QuantityCode");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.QuantitySearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<decimal>("HighValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("HighValue");

                    b.Property<decimal>("LowValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("LowValue");

                    b.Property<int?>("QuantityCodeId")
                        .HasColumnType("int")
                        .HasColumnName("QuantityCodeId");

                    b.Property<decimal?>("SingleValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("SingleValue");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId");

                    b.ToTable("QuantitySearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ReferenceSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("ReferenceResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ReferenceResourceId");

                    b.Property<string>("BaseUri")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("BaseUri");

                    b.Property<short?>("ReferenceResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ReferenceResourceTypeId");

                    b.Property<int?>("ReferenceResourceVersion")
                        .HasColumnType("int")
                        .HasColumnName("ReferenceResourceVersion");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "ReferenceResourceId");

                    b.HasIndex("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "BaseUri", "ReferenceResourceTypeId", "ReferenceResourceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReferenceSearchParam")
                        .HasFilter("[BaseUri] IS NOT NULL AND [ReferenceResourceTypeId] IS NOT NULL");

                    b.ToTable("ReferenceSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<long?>("HistoryTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("HistoryTransactionId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsHistory")
                        .HasColumnType("bit")
                        .HasColumnName("IsHistory");

                    b.Property<bool>("IsRawResourceMetaSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRawResourceMetaSet");

                    b.Property<byte[]>("RawResource")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RawResource");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RequestMethod");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ResourceId");

                    b.Property<string>("SearchParamHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("SearchParamHash");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionId");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId")
                        .HasName("PKC_Resource");

                    b.HasIndex("HistoryTransactionId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ResourceTypeId", "HistoryTransactionId")
                        .HasDatabaseName("IX_ResourceTypeId_HistoryTransactionId")
                        .HasFilter("[HistoryTransactionId] IS NOT NULL");

                    b.HasIndex("ResourceTypeId", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Resource_ResourceTypeId_ResourceId")
                        .HasFilter("[IsHistory] = 0");

                    b.HasIndex("ResourceTypeId", "TransactionId")
                        .HasDatabaseName("IX_ResourceTypeId_TransactionId")
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("ResourceTypeId", "ResourceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_Resource_ResourceTypeId_ResourceId_Version");

                    b.ToTable("Resource", "dbo", t =>
                        {
                            t.HasCheckConstraint("CH_Resource_RawResource_Length", "RawResource > 0x0");
                        });
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTypeEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<short>("ResourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ResourceTypeId"));

                    b.HasKey("Name")
                        .HasName("PKC_ResourceType");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Name"));

                    b.HasIndex("ResourceTypeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ResourceType_ResourceTypeId");

                    b.ToTable("ResourceType", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.SearchParamEntity", b =>
                {
                    b.Property<short>("SearchParamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SearchParamId"));

                    b.Property<bool>("IsPartiallySupported")
                        .HasColumnType("bit");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("SearchParamId")
                        .HasName("PK_SearchParam");

                    b.HasIndex("Uri")
                        .IsUnique()
                        .HasDatabaseName("UQ_SearchParam_Uri");

                    b.ToTable("SearchParam");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.StringSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Text");

                    b.Property<bool>("IsMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMax");

                    b.Property<bool>("IsMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMin");

                    b.Property<string>("TextOverflow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TextOverflow");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "Text");

                    b.ToTable("StringSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.SystemEntity", b =>
                {
                    b.Property<int>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemId"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SystemId")
                        .HasName("PK_System");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UQ_System_Value");

                    b.ToTable("System");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TokenSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Code");

                    b.Property<string>("CodeOverflow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodeOverflow");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "Code");

                    b.HasIndex("SearchParamId", "SystemId", "Code")
                        .HasDatabaseName("IX_TokenSearchParam_SearchParamId_SystemId_Code")
                        .HasFilter("[SystemId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SearchParamId", "SystemId", "Code"), new[] { "ResourceTypeId", "ResourceSurrogateId" });

                    b.HasIndex("SystemId", "Code")
                        .HasDatabaseName("IX_TokenSearchParam_SystemId_Code")
                        .HasFilter("[SystemId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SystemId", "Code"), new[] { "ResourceTypeId", "ResourceSurrogateId" });

                    b.HasIndex("ResourceTypeId", "SearchParamId")
                        .HasDatabaseName("IX_TokenSearchParam_ResourceTypeId_SearchParamId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ResourceTypeId", "SearchParamId"), new[] { "SystemId", "Code" });

                    b.ToTable("TokenSearchParam", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_TokenSearchParam_CodeOverflow", "LEN(Code) = 256 OR CodeOverflow IS NULL");
                        });
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", b =>
                {
                    b.Property<long>("SurrogateIdRangeFirstValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SurrogateIdRangeFirstValue");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SurrogateIdRangeFirstValue"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate")
                        .HasDefaultValueSql("getUTCdate()");

                    b.Property<string>("Definition")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Definition");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FailureReason");

                    b.Property<DateTime>("HeartbeatDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("HeartbeatDate")
                        .HasDefaultValueSql("getUTCdate()");

                    b.Property<DateTime?>("HistoryMovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HistoryMovedDate");

                    b.Property<DateTime?>("InvisibleHistoryRemovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InvisibleHistoryRemovedDate");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsCompleted");

                    b.Property<bool>("IsControlledByClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsControlledByClient");

                    b.Property<bool>("IsHistoryMoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsHistoryMoved");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSuccess");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsVisible");

                    b.Property<long>("SurrogateIdRangeLastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("SurrogateIdRangeLastValue");

                    b.Property<DateTime?>("VisibleDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("VisibleDate");

                    b.HasKey("SurrogateIdRangeFirstValue")
                        .HasName("PKC_Transactions_SurrogateIdRangeFirstValue");

                    b.ToTable("Transactions", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.UriSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("Uri")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Uri");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "Uri");

                    b.ToTable("UriSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.DateTimeSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.NumberSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.QuantitySearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ReferenceSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", "HistoryTransaction")
                        .WithMany("HistorizedResources")
                        .HasForeignKey("HistoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTypeEntity", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .HasPrincipalKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", "Transaction")
                        .WithMany("CreatedResources")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HistoryTransaction");

                    b.Navigation("ResourceType");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.StringSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TokenSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.UriSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTypeEntity", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", b =>
                {
                    b.Navigation("CreatedResources");

                    b.Navigation("HistorizedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
