// <auto-generated />
using System;
using Ignixa.DataLayer.SqlEntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ignixa.DataLayer.SqlEntityFramework.Migrations
{
    [DbContext(typeof(FhirDbContext))]
    [Migration("20251222213143_AddResourceTtlTable")]
    partial class AddResourceTtlTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.BackgroundJobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("HeartbeatDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("OrchestrationInstanceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Progress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Worker")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("JobId")
                        .HasName("PK_BackgroundJobs");

                    b.HasIndex("CreateDate")
                        .HasDatabaseName("IX_BackgroundJobs_CreateDate");

                    b.HasIndex("HeartbeatDate")
                        .HasDatabaseName("IX_BackgroundJobs_HeartbeatDate");

                    b.HasIndex("JobType")
                        .HasDatabaseName("IX_BackgroundJobs_JobType");

                    b.HasIndex("OrchestrationInstanceId")
                        .HasDatabaseName("IX_BackgroundJobs_OrchestrationInstanceId")
                        .HasFilter("[OrchestrationInstanceId] IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BackgroundJobs_Status");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.DateTimeSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDateTime");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDateTime");

                    b.Property<bool>("IsLongerThanADay")
                        .HasColumnType("bit")
                        .HasColumnName("IsLongerThanADay");

                    b.Property<bool>("IsMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMax");

                    b.Property<bool>("IsMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMin");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "StartDateTime");

                    b.ToTable("DateTimeSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.NumberSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<decimal>("HighValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("HighValue");

                    b.Property<decimal>("LowValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("LowValue");

                    b.Property<decimal?>("SingleValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("SingleValue");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId");

                    b.ToTable("NumberSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.PackageResourceEntity", b =>
                {
                    b.Property<long>("PackageResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PackageResourceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PackageResourceId"));

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Canonical");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ContentHash");

                    b.Property<string>("FhirVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FhirVersion");

                    b.Property<DateTimeOffset?>("ImportCompletedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ImportCompletedDate");

                    b.Property<string>("ImportErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ImportErrorMessage");

                    b.Property<DateTimeOffset?>("ImportStartDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ImportStartDate");

                    b.Property<int?>("ImportedConceptCount")
                        .HasColumnType("int")
                        .HasColumnName("ImportedConceptCount");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<DateTimeOffset>("LoadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LoadedDate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PackageId");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PackageVersion");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ResourceId");

                    b.Property<string>("ResourceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResourceJson");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ResourceType");

                    b.Property<string>("TerminologyImportStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TerminologyImportStatus");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Version");

                    b.HasKey("PackageResourceId")
                        .HasName("PK_PackageResource");

                    b.HasIndex("LoadedDate")
                        .HasDatabaseName("IX_PackageResource_LoadedDate");

                    b.HasIndex("Canonical", "Version")
                        .HasDatabaseName("IX_PackageResource_Canonical_Version")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PackageId", "PackageVersion")
                        .HasDatabaseName("IX_PackageResource_Package");

                    b.HasIndex("ResourceType", "Canonical")
                        .HasDatabaseName("IX_PackageResource_ResourceType_Canonical")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PackageId", "PackageVersion", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PackageResource_Identity");

                    b.ToTable("PackageResource", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.QuantityCodeEntity", b =>
                {
                    b.Property<int>("QuantityCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuantityCodeId"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("QuantityCodeId")
                        .HasName("PK_QuantityCode");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuantityCode_Value");

                    b.ToTable("QuantityCode");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.QuantitySearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<decimal>("HighValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("HighValue");

                    b.Property<decimal>("LowValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("LowValue");

                    b.Property<int?>("QuantityCodeId")
                        .HasColumnType("int")
                        .HasColumnName("QuantityCodeId");

                    b.Property<decimal?>("SingleValue")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)")
                        .HasColumnName("SingleValue");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId");

                    b.ToTable("QuantitySearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ReferenceSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("ReferenceResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ReferenceResourceId");

                    b.Property<string>("BaseUri")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("BaseUri");

                    b.Property<short?>("ReferenceResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ReferenceResourceTypeId");

                    b.Property<int?>("ReferenceResourceVersion")
                        .HasColumnType("int")
                        .HasColumnName("ReferenceResourceVersion");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "ReferenceResourceId");

                    b.HasIndex("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "BaseUri", "ReferenceResourceTypeId", "ReferenceResourceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReferenceSearchParam")
                        .HasFilter("[BaseUri] IS NOT NULL AND [ReferenceResourceTypeId] IS NOT NULL");

                    b.ToTable("ReferenceSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<long?>("HistoryTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("HistoryTransactionId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsHistory")
                        .HasColumnType("bit")
                        .HasColumnName("IsHistory");

                    b.Property<bool>("IsRawResourceMetaSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRawResourceMetaSet");

                    b.Property<byte[]>("RawResource")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RawResource");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RequestMethod");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ResourceId");

                    b.Property<string>("SearchParamHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("SearchParamHash");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionId");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId")
                        .HasName("PKC_Resource");

                    b.HasIndex("HistoryTransactionId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ResourceTypeId", "HistoryTransactionId")
                        .HasDatabaseName("IX_ResourceTypeId_HistoryTransactionId")
                        .HasFilter("[HistoryTransactionId] IS NOT NULL");

                    b.HasIndex("ResourceTypeId", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Resource_ResourceTypeId_ResourceId")
                        .HasFilter("[IsHistory] = 0");

                    b.HasIndex("ResourceTypeId", "TransactionId")
                        .HasDatabaseName("IX_ResourceTypeId_TransactionId")
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("ResourceTypeId", "ResourceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_Resource_ResourceTypeId_ResourceId_Version");

                    b.ToTable("Resource", "dbo", t =>
                        {
                            t.HasCheckConstraint("CH_Resource_RawResource_Length", "RawResource > 0x0");
                        });
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTtlEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ResourceId")
                        .UseCollation("Latin1_General_100_CS_AS");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ExpiresAt");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionId");

                    b.HasKey("ResourceTypeId", "ResourceId")
                        .HasName("PK_ResourceTtl");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ResourceTtl_ExpiresAt");

                    b.HasIndex("TransactionId");

                    b.ToTable("ResourceTtl", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTypeEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<short>("ResourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ResourceTypeId"));

                    b.HasKey("Name")
                        .HasName("PKC_ResourceType");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Name"));

                    b.HasIndex("ResourceTypeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ResourceType_ResourceTypeId");

                    b.ToTable("ResourceType", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.SearchParamEntity", b =>
                {
                    b.Property<string>("Uri")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsPartiallySupported")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<short>("SearchParamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SearchParamId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Uri")
                        .HasName("PKC_SearchParam");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Uri"));

                    b.HasIndex("SearchParamId")
                        .IsUnique()
                        .HasDatabaseName("UQ_SearchParam_SearchParamId");

                    b.ToTable("SearchParam");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.StringSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Text");

                    b.Property<bool>("IsMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMax");

                    b.Property<bool>("IsMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMin");

                    b.Property<string>("TextOverflow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TextOverflow");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "Text");

                    b.ToTable("StringSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.SystemEntity", b =>
                {
                    b.Property<int>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemId"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SystemId")
                        .HasName("PK_System");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UQ_System_Value");

                    b.ToTable("System");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermCodeSystemEntity", b =>
                {
                    b.Property<long>("TermCodeSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TermCodeSystemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TermCodeSystemId"));

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("bit")
                        .HasColumnName("CaseSensitive");

                    b.Property<bool>("Compositional")
                        .HasColumnType("bit")
                        .HasColumnName("Compositional");

                    b.Property<int>("ConceptCount")
                        .HasColumnType("int")
                        .HasColumnName("ConceptCount");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Content");

                    b.Property<DateTimeOffset>("ImportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ImportedDate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsHierarchical")
                        .HasColumnType("bit")
                        .HasColumnName("IsHierarchical");

                    b.Property<long>("PackageResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageResourceId");

                    b.Property<int>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Version");

                    b.HasKey("TermCodeSystemId")
                        .HasName("PK_TermCodeSystem");

                    b.HasIndex("PackageResourceId")
                        .HasDatabaseName("IX_TermCodeSystem_PackageResourceId");

                    b.HasIndex("SystemId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_TermCodeSystem_System_Version")
                        .HasFilter("[Version] IS NOT NULL");

                    b.ToTable("TermCodeSystem", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptEntity", b =>
                {
                    b.Property<long>("TermConceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TermConceptId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TermConceptId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Code");

                    b.Property<string>("Definition")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Definition");

                    b.Property<string>("Display")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Display");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<long?>("ParentConceptId")
                        .HasColumnType("bigint")
                        .HasColumnName("ParentConceptId");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PropertiesJson");

                    b.Property<long>("TermCodeSystemId")
                        .HasColumnType("bigint")
                        .HasColumnName("TermCodeSystemId");

                    b.HasKey("TermConceptId")
                        .HasName("PK_TermConcept");

                    b.HasIndex("Display")
                        .HasDatabaseName("IX_TermConcept_Display")
                        .HasFilter("[Display] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Display"), new[] { "TermCodeSystemId", "Code" });

                    b.HasIndex("ParentConceptId", "Level")
                        .HasDatabaseName("IX_TermConcept_Parent")
                        .HasFilter("[ParentConceptId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ParentConceptId", "Level"), new[] { "Code", "Display" });

                    b.HasIndex("TermCodeSystemId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_TermConcept_CodeSystem_Code");

                    b.HasIndex("TermCodeSystemId", "Code", "IsActive")
                        .HasDatabaseName("IX_TermConcept_CodeSystem_Code_Active");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TermCodeSystemId", "Code", "IsActive"), new[] { "Display", "Definition" });

                    b.ToTable("TermConcept", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptMapElementEntity", b =>
                {
                    b.Property<long>("TermConceptMapElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TermConceptMapElementId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TermConceptMapElementId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comment");

                    b.Property<string>("Equivalence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Equivalence");

                    b.Property<int>("GroupIndex")
                        .HasColumnType("int")
                        .HasColumnName("GroupIndex");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SourceCode");

                    b.Property<string>("SourceDisplay")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SourceDisplay");

                    b.Property<int>("SourceSystemId")
                        .HasColumnType("int")
                        .HasColumnName("SourceSystemId");

                    b.Property<string>("TargetCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TargetCode");

                    b.Property<string>("TargetDisplay")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TargetDisplay");

                    b.Property<int?>("TargetSystemId")
                        .HasColumnType("int")
                        .HasColumnName("TargetSystemId");

                    b.Property<long>("TermConceptMapId")
                        .HasColumnType("bigint")
                        .HasColumnName("TermConceptMapId");

                    b.HasKey("TermConceptMapElementId")
                        .HasName("PK_TermConceptMapElement");

                    b.HasIndex("TermConceptMapId");

                    b.HasIndex("SourceSystemId", "SourceCode")
                        .HasDatabaseName("IX_TermConceptMapElement_Source");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceSystemId", "SourceCode"), new[] { "TermConceptMapId", "TargetSystemId", "TargetCode", "Equivalence" });

                    b.HasIndex("TargetSystemId", "TargetCode")
                        .HasDatabaseName("IX_TermConceptMapElement_Target")
                        .HasFilter("[TargetSystemId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TargetSystemId", "TargetCode"), new[] { "TermConceptMapId", "SourceSystemId", "SourceCode", "Equivalence" });

                    b.ToTable("TermConceptMapElement", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptMapEntity", b =>
                {
                    b.Property<long>("TermConceptMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TermConceptMapId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TermConceptMapId"));

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Canonical");

                    b.Property<DateTimeOffset>("ImportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ImportedDate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Name");

                    b.Property<long>("PackageResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageResourceId");

                    b.Property<string>("SourceCanonical")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("SourceCanonical");

                    b.Property<string>("TargetCanonical")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("TargetCanonical");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Version");

                    b.HasKey("TermConceptMapId")
                        .HasName("PK_TermConceptMap");

                    b.HasIndex("PackageResourceId");

                    b.HasIndex("Canonical", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_TermConceptMap_Canonical_Version")
                        .HasFilter("[Version] IS NOT NULL");

                    b.ToTable("TermConceptMap", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermValueSetEntity", b =>
                {
                    b.Property<long>("TermValueSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TermValueSetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TermValueSetId"));

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Canonical");

                    b.Property<int?>("ExpansionCodeCount")
                        .HasColumnType("int")
                        .HasColumnName("ExpansionCodeCount");

                    b.Property<bool>("Immutable")
                        .HasColumnType("bit")
                        .HasColumnName("Immutable");

                    b.Property<DateTimeOffset>("ImportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ImportedDate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("bit")
                        .HasColumnName("IsExpanded");

                    b.Property<bool>("IsPartialExpansion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsPartialExpansion");

                    b.Property<DateTimeOffset?>("LastExpansionDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastExpansionDate");

                    b.Property<string>("PartialExpansionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("PartialExpansionReason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Name");

                    b.Property<long>("PackageResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("PackageResourceId");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Version");

                    b.HasKey("TermValueSetId")
                        .HasName("PK_TermValueSet");

                    b.HasIndex("Canonical")
                        .HasDatabaseName("IX_TermValueSet_Canonical");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Canonical"), new[] { "Version", "IsExpanded" });

                    b.HasIndex("IsExpanded")
                        .HasDatabaseName("IX_TermValueSet_Expanded")
                        .HasFilter("[IsExpanded] = 0");

                    b.HasIndex("PackageResourceId");

                    b.HasIndex("Canonical", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_TermValueSet_Canonical_Version")
                        .HasFilter("[Version] IS NOT NULL");

                    b.ToTable("TermValueSet", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermValueSetExpansionEntity", b =>
                {
                    b.Property<long>("TermValueSetExpansionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TermValueSetExpansionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TermValueSetExpansionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Code");

                    b.Property<string>("Display")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Display");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("Ordinal");

                    b.Property<int>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.Property<string>("SystemVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SystemVersion");

                    b.Property<long>("TermValueSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("TermValueSetId");

                    b.HasKey("TermValueSetExpansionId")
                        .HasName("PK_TermValueSetExpansion");

                    b.HasIndex("Display")
                        .HasDatabaseName("IX_TermValueSetExpansion_Display")
                        .HasFilter("[Display] IS NOT NULL AND [IsActive] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Display"), new[] { "TermValueSetId", "SystemId", "Code" });

                    b.HasIndex("SystemId");

                    b.HasIndex("TermValueSetId", "Ordinal")
                        .HasDatabaseName("IX_TermValueSetExpansion_ValueSet_Ordinal")
                        .HasFilter("[IsActive] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TermValueSetId", "Ordinal"), new[] { "SystemId", "Code", "Display" });

                    b.HasIndex("TermValueSetId", "SystemId", "Code")
                        .HasDatabaseName("IX_TermValueSetExpansion_ValueSet_System_Code")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TermValueSetExpansion", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TokenSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Code");

                    b.Property<string>("CodeOverflow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodeOverflow");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "Code");

                    b.HasIndex("ResourceTypeId", "SearchParamId")
                        .HasDatabaseName("IX_TokenSearchParam_ResourceTypeId_SearchParamId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ResourceTypeId", "SearchParamId"), new[] { "SystemId", "Code" });

                    b.HasIndex("SystemId", "Code")
                        .HasDatabaseName("IX_TokenSearchParam_SystemId_Code")
                        .HasFilter("[SystemId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SystemId", "Code"), new[] { "ResourceTypeId", "ResourceSurrogateId" });

                    b.HasIndex("SearchParamId", "SystemId", "Code")
                        .HasDatabaseName("IX_TokenSearchParam_SearchParamId_SystemId_Code")
                        .HasFilter("[SystemId] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SearchParamId", "SystemId", "Code"), new[] { "ResourceTypeId", "ResourceSurrogateId" });

                    b.ToTable("TokenSearchParam", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_TokenSearchParam_CodeOverflow", "LEN(Code) = 256 OR CodeOverflow IS NULL");
                        });
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", b =>
                {
                    b.Property<long>("SurrogateIdRangeFirstValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SurrogateIdRangeFirstValue");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SurrogateIdRangeFirstValue"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate")
                        .HasDefaultValueSql("getUTCdate()");

                    b.Property<string>("Definition")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Definition");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FailureReason");

                    b.Property<DateTime>("HeartbeatDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("HeartbeatDate")
                        .HasDefaultValueSql("getUTCdate()");

                    b.Property<DateTime?>("HistoryMovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HistoryMovedDate");

                    b.Property<DateTime?>("InvisibleHistoryRemovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InvisibleHistoryRemovedDate");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsCompleted");

                    b.Property<bool>("IsControlledByClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsControlledByClient");

                    b.Property<bool>("IsHistoryMoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsHistoryMoved");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSuccess");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsVisible");

                    b.Property<long>("SurrogateIdRangeLastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("SurrogateIdRangeLastValue");

                    b.Property<DateTime?>("VisibleDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("VisibleDate");

                    b.HasKey("SurrogateIdRangeFirstValue")
                        .HasName("PKC_Transactions_SurrogateIdRangeFirstValue");

                    b.ToTable("Transactions", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.UriSearchParamEntity", b =>
                {
                    b.Property<short>("ResourceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("ResourceTypeId");

                    b.Property<long>("ResourceSurrogateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceSurrogateId");

                    b.Property<short>("SearchParamId")
                        .HasColumnType("smallint")
                        .HasColumnName("SearchParamId");

                    b.Property<string>("Uri")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Uri");

                    b.HasKey("ResourceTypeId", "ResourceSurrogateId", "SearchParamId", "Uri");

                    b.ToTable("UriSearchParam", "dbo");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.DateTimeSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.NumberSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.QuantitySearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ReferenceSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", "HistoryTransaction")
                        .WithMany("HistorizedResources")
                        .HasForeignKey("HistoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTypeEntity", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .HasPrincipalKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", "Transaction")
                        .WithMany("CreatedResources")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HistoryTransaction");

                    b.Navigation("ResourceType");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTtlEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.StringSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermCodeSystemEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.PackageResourceEntity", "PackageResource")
                        .WithMany()
                        .HasForeignKey("PackageResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermCodeSystem_PackageResource");

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.SystemEntity", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TermCodeSystem_System");

                    b.Navigation("PackageResource");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptEntity", "ParentConcept")
                        .WithMany()
                        .HasForeignKey("ParentConceptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TermConcept_Parent");

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermCodeSystemEntity", "CodeSystem")
                        .WithMany()
                        .HasForeignKey("TermCodeSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermConcept_CodeSystem");

                    b.Navigation("CodeSystem");

                    b.Navigation("ParentConcept");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptMapElementEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.SystemEntity", "SourceSystem")
                        .WithMany()
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TermConceptMapElement_SourceSystem");

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.SystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TermConceptMapElement_TargetSystem");

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptMapEntity", "ConceptMap")
                        .WithMany()
                        .HasForeignKey("TermConceptMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermConceptMapElement_ConceptMap");

                    b.Navigation("ConceptMap");

                    b.Navigation("SourceSystem");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermConceptMapEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.PackageResourceEntity", "PackageResource")
                        .WithMany()
                        .HasForeignKey("PackageResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermConceptMap_PackageResource");

                    b.Navigation("PackageResource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermValueSetEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.PackageResourceEntity", "PackageResource")
                        .WithMany()
                        .HasForeignKey("PackageResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermValueSet_PackageResource");

                    b.Navigation("PackageResource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermValueSetExpansionEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.SystemEntity", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TermValueSetExpansion_System");

                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.Terminology.TermValueSetEntity", "ValueSet")
                        .WithMany()
                        .HasForeignKey("TermValueSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermValueSetExpansion_ValueSet");

                    b.Navigation("System");

                    b.Navigation("ValueSet");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TokenSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.UriSearchParamEntity", b =>
                {
                    b.HasOne("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId", "ResourceSurrogateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.ResourceTypeEntity", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Ignixa.DataLayer.SqlEntityFramework.Entities.TransactionEntity", b =>
                {
                    b.Navigation("CreatedResources");

                    b.Navigation("HistorizedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
