namespace Ignixa.Domain.Models;

/// <summary>
/// Represents a bulk export job in the FHIR server.
/// Tracks the state and metadata for an asynchronous $export operation.
/// </summary>
public class BulkExportJob
{
    /// <summary>
    /// Unique identifier for the export job.
    /// </summary>
    public required string JobId { get; init; }

    /// <summary>
    /// Tenant ID that owns this export job.
    /// </summary>
    public required int TenantId { get; init; }

    /// <summary>
    /// Current status of the export job.
    /// </summary>
    public ExportJobStatus Status { get; set; }

    /// <summary>
    /// Resource types to export. If empty, exports all types.
    /// </summary>
    public IReadOnlyCollection<string> ResourceTypes { get; init; } = Array.Empty<string>();

    /// <summary>
    /// Optional start date for filtering resources (exported resources updated >= this date).
    /// </summary>
    public DateTimeOffset? Since { get; init; }

    /// <summary>
    /// Optional type filters (FHIR search query strings per resource type).
    /// Format: { "Observation": "code=http://loinc.org|85354-9", "Condition": "category=encounter-diagnosis" }
    /// </summary>
    public IReadOnlyDictionary<string, string> TypeFilters { get; init; } = new Dictionary<string, string>();

    /// <summary>
    /// Output format for exported files (default: application/fhir+ndjson).
    /// </summary>
    public string OutputFormat { get; init; } = "application/fhir+ndjson";

    /// <summary>
    /// Base path where export files are written.
    /// Format: {baseDir}/{tenantId}/export/{jobId}/
    /// </summary>
    public required string OutputPath { get; init; }

    /// <summary>
    /// Timestamp when the job was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Timestamp when the job started processing.
    /// </summary>
    public DateTimeOffset? StartedAt { get; set; }

    /// <summary>
    /// Timestamp when the job completed (success, failed, or cancelled).
    /// </summary>
    public DateTimeOffset? CompletedAt { get; set; }

    /// <summary>
    /// Error message if the job failed.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Total number of resources exported.
    /// </summary>
    public long TotalResourcesExported { get; set; }

    private readonly Dictionary<string, List<string>> _outputFiles = new();

    /// <summary>
    /// Output files generated by the export (relative paths from OutputPath).
    /// Key: Resource type (e.g., "Patient"), Value: List of file names (e.g., ["Patient_0.ndjson", "Patient_1.ndjson"])
    /// </summary>
    public IReadOnlyDictionary<string, List<string>> OutputFiles => _outputFiles;

    /// <summary>
    /// Adds an output file for a resource type.
    /// </summary>
    public void AddOutputFile(string resourceType, string fileName)
    {
        if (!_outputFiles.ContainsKey(resourceType))
        {
            _outputFiles[resourceType] = new List<string>();
        }

        _outputFiles[resourceType].Add(fileName);
    }

    /// <summary>
    /// Gets the progress percentage (0-100) based on status.
    /// </summary>
    public int ProgressPercentage =>
        Status switch
        {
            ExportJobStatus.Queued => 0,
            ExportJobStatus.InProgress => 50,
            ExportJobStatus.Completed => 100,
            ExportJobStatus.Failed => 0,
            ExportJobStatus.Cancelled => 0,
            _ => 0,
        };

    /// <summary>
    /// Marks the job as started.
    /// </summary>
    public void MarkAsStarted()
    {
        Status = ExportJobStatus.InProgress;
        StartedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Marks the job as completed successfully.
    /// </summary>
    public void MarkAsCompleted()
    {
        Status = ExportJobStatus.Completed;
        CompletedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Marks the job as failed with an error message.
    /// </summary>
    public void MarkAsFailed(string errorMessage)
    {
        Status = ExportJobStatus.Failed;
        CompletedAt = DateTimeOffset.UtcNow;
        ErrorMessage = errorMessage;
    }

    /// <summary>
    /// Marks the job as cancelled.
    /// </summary>
    public void MarkAsCancelled()
    {
        Status = ExportJobStatus.Cancelled;
        CompletedAt = DateTimeOffset.UtcNow;
    }
}
