// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

namespace Ignixa.Domain.Models;

/// <summary>
/// Represents a FHIR conformance resource extracted from an NPM package (IG).
/// Supports multi-version package loading and canonical URL resolution.
/// </summary>
public class PackageResource
{
    /// <summary>
    /// Surrogate primary key (auto-generated by database).
    /// </summary>
    public long PackageResourceId { get; set; }

    /// <summary>
    /// NPM package identifier (e.g., "hl7.fhir.us.core").
    /// </summary>
    public required string PackageId { get; set; }

    /// <summary>
    /// NPM package version using semantic versioning (e.g., "5.0.1", "6.1.0").
    /// </summary>
    public required string PackageVersion { get; set; }

    /// <summary>
    /// FHIR resource type (e.g., "StructureDefinition", "ValueSet", "CodeSystem").
    /// </summary>
    public required string ResourceType { get; set; }

    /// <summary>
    /// Canonical URL of the conformance resource.
    /// Used for resolution and lookups (e.g., "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient").
    /// </summary>
    public required string Canonical { get; set; }

    /// <summary>
    /// Business version of the conformance resource (from resource.version field).
    /// May differ from PackageVersion (e.g., package 5.0.1 might contain resource version 5.0.0).
    /// </summary>
    public string? Version { get; set; }

    /// <summary>
    /// Logical FHIR resource ID (from resource.id field).
    /// </summary>
    public required string ResourceId { get; set; }

    /// <summary>
    /// Full FHIR resource as JSON string.
    /// Stored uncompressed for package resources (immutable, infrequent access).
    /// </summary>
    public required string ResourceJson { get; set; }

    /// <summary>
    /// FHIR version (e.g., "4.0.1" for R4, "4.3.0" for R4B, "5.0.0" for R5).
    /// </summary>
    public required string FhirVersion { get; set; }

    /// <summary>
    /// When this package resource was loaded into the database.
    /// </summary>
    public DateTimeOffset LoadedDate { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Indicates if this package resource is active and should be used for resolution.
    /// Allows soft-deletion of packages without data loss.
    /// </summary>
    public bool IsActive { get; set; } = true;

    // -------------------------------------------------------------------------------------------------
    // Terminology Import Tracking (Phase 1)
    // -------------------------------------------------------------------------------------------------

    /// <summary>
    /// Status of terminology import for this resource (only applies to CodeSystem, ValueSet, ConceptMap).
    /// Null for non-terminology resources (StructureDefinition, SearchParameter, etc.).
    /// </summary>
    public Terminology.TerminologyImportStatus? TerminologyImportStatus { get; set; }

    /// <summary>
    /// SHA256 hash of ResourceJson content to detect changes and avoid re-importing unchanged resources.
    /// Computed when resource is first loaded or updated.
    /// </summary>
    public string? ContentHash { get; set; }

    /// <summary>
    /// When terminology import started (null if not started).
    /// Used to detect stalled imports.
    /// </summary>
    public DateTimeOffset? ImportStartDate { get; set; }

    /// <summary>
    /// When terminology import completed (null if not completed).
    /// Indicates successful extraction to TermCodeSystem/TermValueSet/TermConceptMap tables.
    /// </summary>
    public DateTimeOffset? ImportCompletedDate { get; set; }

    /// <summary>
    /// Error message if import failed (null if succeeded or pending).
    /// Contains exception message and stack trace for troubleshooting.
    /// </summary>
    public string? ImportErrorMessage { get; set; }

    /// <summary>
    /// Number of concepts/codes imported (for CodeSystem/ValueSet).
    /// Used for progress tracking and metrics.
    /// </summary>
    public int? ImportedConceptCount { get; set; }

    // -------------------------------------------------------------------------------------------------
    // Helper Methods
    // -------------------------------------------------------------------------------------------------

    /// <summary>
    /// Returns true if this resource is a terminology resource (CodeSystem, ValueSet, ConceptMap).
    /// </summary>
    public bool IsTerminologyResource()
    {
        return ResourceType is "CodeSystem" or "ValueSet" or "ConceptMap";
    }

    /// <summary>
    /// Computes SHA256 hash of ResourceJson for change detection.
    /// Use this to set ContentHash after loading or updating a resource.
    /// </summary>
    public string ComputeContentHash()
    {
        byte[] contentBytes = System.Text.Encoding.UTF8.GetBytes(ResourceJson);
        byte[] hashBytes = System.Security.Cryptography.SHA256.HashData(contentBytes);
        return Convert.ToHexString(hashBytes);
    }
}
