namespace Ignixa.NarrativeGenerator;

/// <summary>
/// Marker class for localization resources.
/// This class is used as a type parameter for IStringLocalizer to access the NarrativeStrings.resx resources.
/// The actual implementation is generated by PublicResXFileCodeGenerator in NarrativeStrings.Designer.cs.
/// </summary>
public class NarrativeStrings
{
}
